import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = resolve(root, "schema/contract.v2.schema.json");
const schemaText = await readFile(schemaPath, "utf8");
const schema = JSON.parse(schemaText);
const check = process.argv.includes("--check");

const supported = new Set([
  "$schema", "$id", "$ref", "$defs", "title", "description", "type", "const", "enum", "pattern", "format",
  "minimum", "maximum", "minLength", "maxLength", "minItems", "default", "oneOf", "properties", "required", "items", "additionalProperties",
]);

function audit(node, path = "#") {
  if (node === true || node === false) return;
  if (!node || typeof node !== "object" || Array.isArray(node)) throw new Error(`invalid schema node at ${path}`);
  for (const key of Object.keys(node)) if (!supported.has(key)) throw new Error(`unsupported JSON Schema keyword ${key} at ${path}`);
  if (node.$ref && !/^#\/\$defs\/[A-Za-z][A-Za-z0-9]*$/.test(node.$ref)) throw new Error(`unsupported ref ${node.$ref}`);
  if (node.oneOf) node.oneOf.forEach((item, index) => audit(item, `${path}/oneOf/${index}`));
  if (node.properties) Object.entries(node.properties).forEach(([key, value]) => audit(value, `${path}/properties/${key}`));
  if (node.items) audit(node.items, `${path}/items`);
  if (node.additionalProperties && typeof node.additionalProperties === "object") audit(node.additionalProperties, `${path}/additionalProperties`);
  if (node.$defs) Object.entries(node.$defs).forEach(([key, value]) => audit(value, `${path}/$defs/${key}`));
}
audit(schema);

const defs = schema.$defs;
const refName = (ref) => ref.slice(ref.lastIndexOf("/") + 1);
const pascal = (value) => value.replace(/(^|[^A-Za-z0-9]+)([A-Za-z0-9])/g, (_, __, ch) => ch.toUpperCase()).replace(/[^A-Za-z0-9]/g, "") || "Value";
const rustField = (value) => ({ type: "r#type", ref: "r#ref", self: "r#self", match: "r#match" }[value] ?? value.replace(/[A-Z]/g, (c) => `_${c.toLowerCase()}`));

function tsType(node) {
  if (!node || Object.keys(node).length === 0) return "unknown";
  if (node.$ref) return refName(node.$ref);
  if (node.oneOf) return node.oneOf.map(tsType).join(" | ");
  if (node.const !== undefined) return JSON.stringify(node.const);
  if (node.enum) return node.enum.map((value) => JSON.stringify(value)).join(" | ");
  if (node.type === "string") return "string";
  if (node.type === "integer" || node.type === "number") return "number";
  if (node.type === "boolean") return "boolean";
  if (node.type === "array") return `Array<${tsType(node.items ?? {})}>`;
  if (node.type === "object") {
    const props = node.properties ?? {};
    if (Object.keys(props).length === 0) return node.additionalProperties === true ? "Record<string, unknown>" : node.additionalProperties ? `Record<string, ${tsType(node.additionalProperties)}>` : "Record<string, never>";
    const required = new Set(node.required ?? []);
    return `{ ${Object.entries(props).map(([key, value]) => `${JSON.stringify(key)}${required.has(key) ? "" : "?"}: ${tsType(value)};`).join(" ")} }`;
  }
  throw new Error(`cannot emit TypeScript for ${JSON.stringify(node)}`);
}

function rustType(node, boxed = false) {
  let result;
  if (!node || Object.keys(node).length === 0) result = "serde_json::Value";
  else if (node.$ref) result = refName(node.$ref);
  else if (node.oneOf) result = "serde_json::Value";
  else if (node.const !== undefined || node.enum || node.type === "string") result = "String";
  else if (node.type === "integer") result = "u64";
  else if (node.type === "number") result = "f64";
  else if (node.type === "boolean") result = "bool";
  else if (node.type === "array") result = `Vec<${rustType(node.items ?? {})}>`;
  else if (node.type === "object") {
    const props = node.properties ?? {};
    if (Object.keys(props).length !== 0) result = "serde_json::Value";
    else if (node.additionalProperties === true) result = "std::collections::BTreeMap<String, serde_json::Value>";
    else if (node.additionalProperties) result = `std::collections::BTreeMap<String, ${rustType(node.additionalProperties)}>`;
    else result = "std::collections::BTreeMap<String, serde_json::Value>";
  } else throw new Error(`cannot emit Rust for ${JSON.stringify(node)}`);
  return boxed && !["String", "bool", "u64", "f64", "serde_json::Value"].includes(result) ? `Box<${result}>` : result;
}

const ts = [
  "// @generated by scripts/generate.mjs from schema/contract.v2.schema.json. DO NOT EDIT.",
  ...Object.entries(defs).map(([name, node]) => {
    if (node.type === "object" && Object.keys(node.properties ?? {}).length > 0) return `export interface ${name} ${tsType(node)}`;
    return `export type ${name} = ${tsType(node)};`;
  }),
  `export type ContractDocument = ${schema.oneOf.map(tsType).join(" | ")};`,
  `export const CONTRACT_SCHEMA = ${JSON.stringify(schema, null, 2)} as const;`,
].join("\n\n");

const rust = [
  "// @generated by scripts/generate.mjs from schema/contract.v2.schema.json. DO NOT EDIT.",
  "#![allow(clippy::large_enum_variant)]",
  "use serde::{Deserialize, Serialize};",
  ...Object.entries(defs).map(([name, node]) => {
    if (node.oneOf) {
      const variants = node.oneOf.map((item, index) => ({ name: item.$ref ? refName(item.$ref) : `Inline${index}`, type: item.$ref ? refName(item.$ref) : rustType(item) }));
      return `#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(untagged)]\npub enum ${name} {\n${variants.map(({ name: variant, type }) => `    ${pascal(variant.replace(/(?:Ref|Event|Option)$/, ""))}(${type}),`).join("\n")}\n}`;
    }
    if (node.type === "string" && node.enum) {
      return `#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\npub enum ${name} {\n${node.enum.map((value) => `    #[serde(rename = ${JSON.stringify(value)})]\n    ${pascal(value)},`).join("\n")}\n}`;
    }
    if (node.type === "object" && Object.keys(node.properties ?? {}).length > 0) {
      const required = new Set(node.required ?? []);
      const fields = Object.entries(node.properties).map(([key, value]) => {
        const optional = !required.has(key);
        const recursive = value.$ref && (refName(value.$ref) === name || (name === "NotCondition" && refName(value.$ref) === "Condition"));
        const ty = rustType(value, recursive);
        return `    #[serde(rename = ${JSON.stringify(key)}${optional ? ", default, skip_serializing_if = \"Option::is_none\"" : ""})]\n    pub ${rustField(key)}: ${optional ? `Option<${ty}>` : ty},`;
      }).join("\n");
      return `#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(deny_unknown_fields)]\npub struct ${name} {\n${fields}\n}`;
    }
    return `pub type ${name} = ${rustType(node)};`;
  }),
  `#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(untagged)]\npub enum ContractDocument {\n    PluginManifest(PluginManifest),\n    ExecuteRequest(ExecuteRequest),\n    JobEvent(JobEvent),\n}`,
  `pub const CONTRACT_SCHEMA_JSON: &str = r###"${JSON.stringify(schema)}"###;`,
].join("\n\n");

async function output(path, content) {
  if (check) {
    const current = await readFile(path, "utf8").catch(() => "");
    if (current.replace(/\r\n/g, "\n") !== content) throw new Error(`generated file is stale: ${path}`);
  } else await writeFile(path, content);
}

await output(resolve(root, "ts/generated.ts"), ts);
await output(resolve(root, "src/generated.rs"), rust);
