use crate::{Document, DocumentKind, GenericTool, InputKind, RendererKind, ToolCapabilities, ToolError, ToolLimits, ToolManifest, ToolOperation, ToolResult};
use serde::{Deserialize, Serialize};
use serde_json::Value;

pub const DEFAULT_MAX_INPUT_BYTES: usize = 32 * 1024 * 1024;
pub const DEFAULT_MAX_OUTPUT_BYTES: usize = 64 * 1024 * 1024;
#[derive(Debug, Clone, Copy, PartialEq, Eq)] pub enum TextUtilityKind { Url, Html, Unicode }
#[derive(Debug, Clone, Serialize, Deserialize)] #[serde(rename_all="camelCase", default)] pub struct TextUtilityOptions { pub max_output_bytes: Option<usize> }
impl Default for TextUtilityOptions { fn default()->Self { Self{max_output_bytes:Some(DEFAULT_MAX_OUTPUT_BYTES)} } }
fn invalid(op:&str,msg:impl Into<String>,position:usize)->ToolError { ToolError::InvalidText{operation:op.into(),message:msg.into(),position} }
fn bounded(s:String,max:usize)->Result<Document,ToolError>{ if s.len()>max { return Err(ToolError::ResourceLimit{message:format!("output exceeds {max} bytes")}); } Ok(Document::from_text(s).with_kind(DocumentKind::Text).with_mime("text/plain")) }

pub fn transform_text(input:&Document,kind:TextUtilityKind,operation:&str,options:&TextUtilityOptions)->Result<ToolResult,ToolError>{
 let text=input.as_text().map_err(|_|ToolError::InvalidUtf8)?;
 let output=match(kind,operation){
  (TextUtilityKind::Url,"encode")=>text.as_bytes().iter().map(|b|if b.is_ascii_alphanumeric()||b"-._~".contains(b){(*b as char).to_string()}else{format!("%{b:02X}")}).collect::<String>(),
  (TextUtilityKind::Url,"decode")=>{let mut o=Vec::with_capacity(text.len());let b=text.as_bytes();let mut i=0;while i<b.len(){if b[i]==b'%' {if i+2>=b.len(){return Err(invalid(operation,"percent escape is truncated",i))}let h=(b[i+1]as char).to_digit(16);let l=(b[i+2]as char).to_digit(16);if h.is_none()||l.is_none(){return Err(invalid(operation,"percent escape must use hexadecimal digits",i))}o.push((h.unwrap()*16+l.unwrap())as u8);i+=3}else{o.push(b[i]);i+=1}}String::from_utf8(o).map_err(|e|invalid(operation,"decoded bytes are not valid UTF-8",e.utf8_error().valid_up_to()))?},
  (TextUtilityKind::Html,"escape")=>text.chars().map(|c|match c{'&'=>"&amp;".into(),'<'=>"&lt;".into(),'>'=>"&gt;".into(),'"'=>"&quot;".into(),'\''=>"&#39;".into(),_=>c.to_string()}).collect::<String>(),
  (TextUtilityKind::Html,"unescape")=>unescape_html(text,operation)?,
  (TextUtilityKind::Unicode,"encode")=>{let mut s=String::new();for c in text.chars(){let n=c as u32;if c.is_ascii()&&!c.is_control(){s.push(c)}else if n<=0xffff{s.push_str(&format!("\\u{n:04X}"))}else{let v=n-0x10000;s.push_str(&format!("\\u{:04X}\\u{:04X}",0xD800+(v>>10),0xDC00+(v&0x3ff)))}}s},
  (TextUtilityKind::Unicode,"decode")=>decode_unicode(text,operation)?,
  _=>return Err(ToolError::UnsupportedOperation{tool_id:"text.utility".into(),operation_id:operation.into()})};
 Ok(ToolResult{output:bounded(output,options.max_output_bytes.unwrap_or(DEFAULT_MAX_OUTPUT_BYTES).min(DEFAULT_MAX_OUTPUT_BYTES))?,diagnostics:Vec::new()})
}
fn unescape_html(text:&str,op:&str)->Result<String,ToolError>{let mut o=String::new();let mut i=0;while i<text.len(){if text.as_bytes()[i]!=b'&'{let c=text[i..].chars().next().unwrap();o.push(c);i+=c.len_utf8();continue}let end=text[i..].find(';').map(|n|i+n).ok_or_else(||invalid(op,"entity is missing ';'",i))?;let t=&text[i+1..end];let c=match t{"amp"=>'&',"lt"=>'<',"gt"=>'>',"quot"=>'"',"apos"|"#39"=>'\'',_=>{if let Some(h)=t.strip_prefix("#x").or_else(||t.strip_prefix("#X")){char::from_u32(u32::from_str_radix(h,16).map_err(|_|invalid(op,"invalid numeric entity",i))?).ok_or_else(||invalid(op,"numeric entity is not a Unicode scalar",i))?}else if let Some(d)=t.strip_prefix('#'){char::from_u32(d.parse().map_err(|_|invalid(op,"invalid numeric entity",i))?).ok_or_else(||invalid(op,"numeric entity is not a Unicode scalar",i))?}else{return Err(invalid(op,"unknown HTML entity",i))}}};o.push(c);i=end+1}Ok(o)}
fn decode_unicode(text:&str,op:&str)->Result<String,ToolError>{let mut o=String::new();let mut i=0;while i<text.len(){if !text[i..].starts_with("\\u"){let c=text[i..].chars().next().unwrap();o.push(c);i+=c.len_utf8();continue}if i+6>text.len(){return Err(invalid(op,"Unicode escape is truncated",i))}let n=u32::from_str_radix(&text[i+2..i+6],16).map_err(|_|invalid(op,"Unicode escape must contain four hexadecimal digits",i))?;i+=6;if(0xD800..=0xDBFF).contains(&n){if !text[i..].starts_with("\\u")||i+6>text.len(){return Err(invalid(op,"high surrogate must be followed by a low surrogate",i))}let l=u32::from_str_radix(&text[i+2..i+6],16).map_err(|_|invalid(op,"invalid low surrogate",i))?;if !(0xDC00..=0xDFFF).contains(&l){return Err(invalid(op,"invalid low surrogate",i))}i+=6;o.push(char::from_u32(0x10000+((n-0xD800)<<10)+l-0xDC00).unwrap())}else if(0xDC00..=0xDFFF).contains(&n){return Err(invalid(op,"unexpected low surrogate",i-6))}else{o.push(char::from_u32(n).unwrap())}}Ok(o)}

pub struct TextUtilityTool{manifest:ToolManifest,kind:TextUtilityKind}
impl TextUtilityTool{pub fn new(kind:TextUtilityKind)->Self{let(id,label,ops)=match kind{TextUtilityKind::Url=>("text.url","URL Encode / Decode",vec![("encode","Encode"),("decode","Decode")]),TextUtilityKind::Html=>("text.html","HTML Escape / Unescape",vec![("escape","Escape"),("unescape","Unescape")]),TextUtilityKind::Unicode=>("text.unicode","Unicode Escape / Unescape",vec![("encode","Escape"),("decode","Unescape")])};Self{kind,manifest:ToolManifest{id:id.into(),label:label.into(),contract_version:1,input_kinds:vec![InputKind::Text],limits:ToolLimits{max_input_bytes:Some(DEFAULT_MAX_INPUT_BYTES as u64),max_output_bytes:Some(DEFAULT_MAX_OUTPUT_BYTES as u64)},capabilities:ToolCapabilities{deterministic:true,supports_preview:true,supports_streaming:true,cancellation:true,progress:true,needs_filesystem:false,needs_network:false,needs_secrets:false},operations:ops.into_iter().map(|(id,label)|ToolOperation{id:id.into(),label:label.into(),default_options:Value::Object(Default::default())}).collect(),renderer:RendererKind::Text}}}}
impl GenericTool for TextUtilityTool{fn manifest(&self)->&ToolManifest{&self.manifest}fn execute(&self,op:&str,input:&Document,options:&Value)->Result<ToolResult,ToolError>{let o:TextUtilityOptions=serde_json::from_value(options.clone()).map_err(|e|ToolError::InvalidOptions{message:e.to_string()})?;transform_text(input,self.kind,op,&o)}}

#[cfg(test)]mod tests{use super::*;#[test]fn url_round_trip(){let d=Document::from_text("café / ?");let e=transform_text(&d,TextUtilityKind::Url,"encode",&Default::default()).unwrap();assert_eq!(e.output.as_text().unwrap(),"caf%C3%A9%20%2F%20%3F");let r=transform_text(&e.output,TextUtilityKind::Url,"decode",&Default::default()).unwrap();assert_eq!(r.output.as_text().unwrap(),"café / ?")}#[test]fn malformed(){assert!(transform_text(&Document::from_text("%G0"),TextUtilityKind::Url,"decode",&Default::default()).is_err());assert!(transform_text(&Document::from_text("&wat;"),TextUtilityKind::Html,"unescape",&Default::default()).is_err());assert!(transform_text(&Document::from_text("\\uD800"),TextUtilityKind::Unicode,"decode",&Default::default()).is_err())}#[test]fn round_trips(){for(k,e,d)in[(TextUtilityKind::Html,"escape","unescape"),(TextUtilityKind::Unicode,"encode","decode")]{let x=transform_text(&Document::from_text("<é 😀>"),k,e,&Default::default()).unwrap();let y=transform_text(&x.output,k,d,&Default::default()).unwrap();assert_eq!(y.output.as_text().unwrap(),"<é 😀>")}}#[test]fn limit(){let o=TextUtilityOptions{max_output_bytes:Some(2)};assert!(transform_text(&Document::from_text("hello"),TextUtilityKind::Url,"encode",&o).is_err())}}
