// @generated by plugin-discovery. DO NOT EDIT.
#[derive(Debug, Clone, Copy)]
pub struct ExecutorDescriptor { pub plugin_id: &'static str, pub processor: &'static str }

pub static EXECUTORS: &[ExecutorDescriptor] = &[
  ExecutorDescriptor { plugin_id: "convert.yaml", processor: "yaml/processor.mjs" },
  ExecutorDescriptor { plugin_id: "encoding.base64-text", processor: "base64-text/processor.mjs" },
  ExecutorDescriptor { plugin_id: "encoding.hash", processor: "hash/processor.mjs" },
  ExecutorDescriptor { plugin_id: "examples.echo", processor: "examples/processor.mjs" },
  ExecutorDescriptor { plugin_id: "format.html", processor: "html/processor.mjs" },
  ExecutorDescriptor { plugin_id: "generate.examples", processor: "example-strings/processor.mjs" },
  ExecutorDescriptor { plugin_id: "identity.uuid", processor: "uuid/processor.mjs" },
  ExecutorDescriptor { plugin_id: "number.base", processor: "number-base/processor.mjs" },
  ExecutorDescriptor { plugin_id: "security.jwt", processor: "jwt/processor.mjs" },
  ExecutorDescriptor { plugin_id: "structured.json", processor: "json/processor.mjs" },
  ExecutorDescriptor { plugin_id: "text.case", processor: "string-case/processor.mjs" },
  ExecutorDescriptor { plugin_id: "text.compare", processor: "diff/processor.mjs" },
  ExecutorDescriptor { plugin_id: "text.escaping", processor: "escaping/processor.mjs" },
  ExecutorDescriptor { plugin_id: "text.find-replace", processor: "find-replace/processor.mjs" },
  ExecutorDescriptor { plugin_id: "time.unix", processor: "time/processor.mjs" },
  ExecutorDescriptor { plugin_id: "web.url", processor: "url/processor.mjs" },
];
