import './styles.css';
import { native, chooseFile, chooseOutput, openDocument, closeDocument, readPreview, saveResult, startOperation, cancelOperation, jobStatus, subscribeJobs, type FileDocument, type Format, type Operation, type JobFinished, type JobProgress } from './bridge';

const $ = <T extends HTMLElement = HTMLElement>(s:string) => document.querySelector<T>(s)!;
const docs = new Map<string,FileDocument>(); let active:string|null=null; let job:string|null=null; let current:JobFinished|null=null; let poll:number|null=null; let lastOperation:Operation='format';
type Pending = { kind:'progress'|'finished'; event:JobProgress|JobFinished }; let pending:Pending[]=[];
const preview=$('#preview') as HTMLTextAreaElement, output=$('#result-output') as HTMLTextAreaElement|null, select=$('#format') as HTMLSelectElement, palette=$('#palette') as HTMLDialogElement, search=$('#palette-search') as HTMLInputElement;
const bytes=(v:number|null|undefined) => { if(typeof v!=='number'||!Number.isFinite(v)) return '—'; const u=['B','KB','MB','GB']; let n=v,i=0; while(n>=1024&&i<3){n/=1024;i++;} return (i===0||n>=100?n.toFixed(0):n.toFixed(1))+' '+u[i]; };
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c));
const setStatus=(s:string)=>$('#status').textContent=s;
const fail=(s:string)=>{ $('#error').textContent=s; $('#error').hidden=false; setStatus('Action failed'); };
const clearError=()=>{ $('#error').hidden=true; };

function renderTabs(){const root=$('#tabs');root.innerHTML=docs.size?'':'<span class="empty-tab">Your workspace</span>';docs.forEach(d=>{const b=document.createElement('button');b.className='tab '+(d.id===active?'active':'');b.role='tab';b.ariaSelected=String(d.id===active);b.title=d.path;b.innerHTML='<span class="file-dot '+d.format+'"></span><span class="tab-name">'+esc(d.name)+'</span><span class="tab-close" title="Close document" aria-label="Close document">×</span>';b.onclick=()=>{active=d.id;current=null;render();renderTabs();};b.querySelector('.tab-close')?.addEventListener('click',e=>{e.stopPropagation();void closeTab(d.id);});root.append(b);});}
async function closeTab(id:string){try{await closeDocument(id);}catch(e){fail(e instanceof Error?e.message:String(e));return;}docs.delete(id);if(active===id){active=docs.keys().next().value||null;current=null;}renderTabs();render();}
function render(){const d=active?docs.get(active):undefined,has=!!d;$('#empty-state').hidden=has;preview.hidden=!has;select.disabled=!has;['inspect','format-file','minify-file'].forEach(id=>$('#'+id).toggleAttribute('disabled',!has||!!job));if(!d){preview.value='';$('#preview-meta').textContent='Open a JSON, CSV, or text file';$('#source-name').textContent='No document open';$('#source-size').textContent='—';$('#source-format').textContent='—';$('#encoding').textContent='—';$('#result-empty').hidden=false;$('#result-content').hidden=true;return;}preview.value=d.preview;select.value=d.format;$('#preview-meta').textContent=(d.truncated?'First 64 KiB · ':'')+bytes(d.size)+' · '+d.format.toUpperCase();$('#preview-limit').textContent=d.truncated?'Preview limited to 64 KiB · Full-file processing':'Bounded preview · Full-file processing';$('#encoding').textContent=d.encoding+' · Read only';$('#source-name').textContent=d.name;$('#source-size').textContent=bytes(d.size);$('#source-format').textContent=d.format.toUpperCase();if(!current){$('#result-empty').hidden=false;$('#result-content').hidden=true;}}
async function openPath(p:string){clearError();if(!native){fail('The native Rust engine is unavailable in this browser preview. Open the desktop app to choose a file.');return;}try{setStatus('Reading bounded preview…');const d=await openDocument(p);docs.set(d.id,d);active=d.id;current=null;renderTabs();render();setStatus('Loaded · formatting the complete file…');void run('format');}catch(e){fail(e instanceof Error?e.message:String(e));}}
async function openFile(){if(!native){fail('The native Rust engine is unavailable in this browser preview. Open the desktop app to choose a file.');return;}try{const p=await chooseFile();if(p)await openPath(p);}catch(e){fail(e instanceof Error?e.message:String(e));}}
async function run(op:Operation){const d=active?docs.get(active):undefined;if(!d||job)return;clearError();current=null;render();if(op!=='inspect'&&d.format!=='json'){fail('Formatting and minifying currently support JSON documents only.');return;}try{await eventsReady;$('#job-panel').hidden=false;$('#job-title').textContent=op[0].toUpperCase()+op.slice(1)+' · '+d.name;$('#job-phase').textContent='Starting…';($('#job-progress') as HTMLProgressElement).value=0;setStatus(op[0].toUpperCase()+op.slice(1)+'ing complete file…');const s=await startOperation(d.id,op,select.value as Format);job=s.jobId;render();drain(s.jobId);if(job===s.jobId)startPoll(s.jobId);}catch(e){$('#job-panel').hidden=true;job=null;render();fail(e instanceof Error?e.message:String(e));}}
function progress(e:JobProgress){if(!job||e.jobId!==job){pending.push({kind:'progress',event:e});if(pending.length>48)pending=pending.slice(-48);return;}const p=e.totalBytes?Math.min(100,e.bytesProcessed/e.totalBytes*100):0;($('#job-progress') as HTMLProgressElement).value=p;$('#job-phase').textContent=e.phase;$('#job-bytes').textContent=bytes(e.bytesProcessed)+' of '+bytes(e.totalBytes);$('#job-percent').textContent=Math.round(p)+'%';}
function finished(e:JobFinished){if(!job||e.jobId!==job){pending.push({kind:'finished',event:e});if(pending.length>48)pending=pending.slice(-48);return;}void showFinished(e);}
async function showFinished(e:JobFinished){if(poll!==null){clearInterval(poll);poll=null;}job=null;current=e;render();$('#job-panel').hidden=true;const state=$('#result-state');state.className='result-state '+(e.ok?'ok':e.cancelled?'cancelled':'failed');state.textContent=e.ok?'✓ Completed successfully':e.cancelled?'○ Cancelled':'● '+(e.error||'Operation failed');const rows:Array<[string,string]>=[['Elapsed',e.elapsedMs+' ms'],['Input',bytes(e.inputBytes)]];if(typeof e.outputBytes==='number')rows.push(['Output',bytes(e.outputBytes)]);rows.push(['Status',e.ok?(e.resultDocumentId?'Ready to review':'Saved'):'No output']);$('#result-metrics').innerHTML=rows.map(r=>'<div><dt>'+r[0]+'</dt><dd>'+esc(r[1])+'</dd></div>').join('');$('#result-summary').textContent=typeof e.summary==='string'?e.summary:JSON.stringify(e.summary??{},null,2);$('#result-empty').hidden=true;$('#result-content').hidden=false;const save=$('#save-result') as HTMLButtonElement|null;if(save)save.hidden=!e.ok||!e.resultDocumentId;if(output)output.hidden=true;if(e.ok&&e.resultDocumentId&&output){try{const r=await readPreview(e.resultDocumentId,0);output.value=r.preview;output.hidden=false;$('#result-output-meta').textContent=r.truncated?'Formatted preview · first 64 KiB':'Formatted output';}catch(x){fail(x instanceof Error?x.message:String(x));}}setStatus(e.ok?'Ready · result shown on the right':e.cancelled?'Cancelled':'Operation failed');}
function drain(id:string){const ev=pending.filter(x=>x.event.jobId===id);pending=pending.filter(x=>x.event.jobId!==id);ev.forEach(x=>x.kind==='progress'?progress(x.event as JobProgress):void showFinished(x.event as JobFinished));}
function startPoll(id:string){if(poll!==null)clearInterval(poll);poll=window.setInterval(()=>{if(job!==id)return;void jobStatus(id).then(r=>{if(r&&job===id)void showFinished(r);}).catch(()=>undefined);},180);}
async function saveCurrent(){const id=current?.resultDocumentId,d=active?docs.get(active):undefined;if(!id||!d)return;try{const path=await chooseOutput(d,lastOperation);if(!path)return;await saveResult(id,path);$('#output-path').textContent=path;$('#saved-output').hidden=false;setStatus('Saved formatted copy');}catch(e){fail(e instanceof Error?e.message:String(e));}}

const commands:Array<[string,string,()=>void]>=[['Open file','Choose a local document',()=>void openFile()],['Inspect document','Analyze the complete file',()=>void run('inspect')],['Format JSON','Show readable JSON on the right',()=>void run('format')],['Minify JSON','Show compact JSON on the right',()=>void run('minify')]];
const info:Record<string,{title:string;subtitle:string;implemented:boolean}>={'structured-json':{title:'JSON',subtitle:'Inspect, validate and format large files',implemented:true},'text-regex':{title:'Text & Regex',subtitle:'Transform, test and extract text',implemented:false},diff:{title:'Diff & Compare',subtitle:'Compare, merge and review files',implemented:false},structured:{title:'Structured data',subtitle:'JSON, YAML, CSV and XML tools',implemented:true},encoding:{title:'Encoding & IDs',subtitle:'Base64, URL, UUID and hashes',implemented:false},time:{title:'Time & Numbers',subtitle:'Timestamps, cron and bases',implemented:false},'web-api':{title:'Web & API',subtitle:'HTTP, cURL and JWT tools',implemented:false},text:{title:'Text utilities',subtitle:'Encode, decode and inspect',implemented:false},hash:{title:'Hash generator',subtitle:'Checksums and digests',implemented:false},curl:{title:'cURL to code',subtitle:'Convert HTTP requests',implemented:false},ids:{title:'UUID & timestamps',subtitle:'Generate and convert',implemented:false}};
document.querySelectorAll<HTMLButtonElement>('.tool-item').forEach(item=>item.onclick=()=>{const i=info[item.dataset.tool||''];if(!i)return;if(!i.implemented){fail(i.title+' is coming next. JSON is the first production tool in this preview.');return;}document.querySelectorAll('.tool-item').forEach(x=>x.classList.remove('active'));item.classList.add('active');$('#active-tool-label').textContent=i.title;$('#active-tool-title').textContent=i.title;$('#active-tool-subtitle').textContent=i.subtitle;});
function renderCommands(){paletteIndex=-1;const q=search.value.toLowerCase(),shown=commands.filter(c=>c[0].toLowerCase().includes(q)||c[1].toLowerCase().includes(q));$('#command-list').innerHTML=shown.map((c,i)=>'<button data-i="'+i+'"><span class="command-glyph">⌁</span><span><strong>'+esc(c[0])+'</strong><small>'+esc(c[1])+'</small></span><kbd>↵</kbd></button>').join('');$('#command-list').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{palette.close();shown[Number(b.dataset.i)]?.[2]();});}
$('#open-file').onclick=()=>void openFile();$('#empty-open').onclick=()=>void openFile();$('#inspect').onclick=()=>void run('inspect');$('#format-file').onclick=()=>void run('format');$('#minify-file').onclick=()=>void run('minify');$('#save-result').onclick=()=>void saveCurrent();$('#cancel-job').onclick=()=>{if(job)void cancelOperation(job).catch(e=>fail(String(e)));};$('#palette-open').onclick=()=>{renderCommands();palette.showModal();search.focus();};$('#palette-close').onclick=()=>palette.close();search.oninput=renderCommands;document.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();renderCommands();palette.showModal();search.focus();}if(e.key==='Escape'&&palette.open)palette.close();};
if(!native){$('#browser-notice').hidden=false;$('#engine-dot').classList.add('offline');$('#engine-status').textContent='Browser preview · native engine unavailable';setStatus('Preview only');}
const eventsReady=subscribeJobs(progress,finished).catch(e=>{if(native)fail('Could not connect to operation events: '+String(e));});renderTabs();render();








const toolSearch=$('#tool-search') as HTMLInputElement;
toolSearch.oninput=()=>{const q=toolSearch.value.trim().toLowerCase();document.querySelectorAll<HTMLElement>('.tool-item').forEach(item=>{item.hidden=!!q&&!item.textContent!.toLowerCase().includes(q);});};
$('#sidebar-collapse').onclick=()=>{$('.sidebar').classList.toggle('collapsed');};
const dropTarget=$('#document-panel');
dropTarget.addEventListener('dragover',e=>{e.preventDefault();dropTarget.classList.add('drag-over');});
dropTarget.addEventListener('dragleave',()=>dropTarget.classList.remove('drag-over'));
dropTarget.addEventListener('drop',e=>{e.preventDefault();dropTarget.classList.remove('drag-over');const file=e.dataTransfer?.files?.[0] as (File&{path?:string})|undefined;if(file?.path)void openPath(file.path);else fail('The dropped file path is unavailable in this preview. Use Open file instead.');});
let paletteIndex=-1;
function movePalette(delta:number){const items=[...document.querySelectorAll<HTMLButtonElement>('#command-list button')];if(!items.length)return;paletteIndex=(paletteIndex+delta+items.length)%items.length;items.forEach((item,i)=>item.classList.toggle('selected',i===paletteIndex));items[paletteIndex].focus();}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='o'){e.preventDefault();void openFile();return;}if(!palette.open)return;if(e.key==='ArrowDown'){e.preventDefault();movePalette(1);}else if(e.key==='ArrowUp'){e.preventDefault();movePalette(-1);}else if(e.key==='Enter'){e.preventDefault();const item=document.querySelector<HTMLButtonElement>('#command-list button.selected');item?.click();}});