import './styles.css';
import { native, chooseFile, chooseOutput, openDocument, closeDocument, readPreview, saveResult, runTool, listTools, cancelOperation, jobStatus, subscribeJobs, type FileDocument, type Operation, type JobFinished, type JobProgress, type RendererKind, type ToolManifest } from './bridge';

const $ = <T extends HTMLElement = HTMLElement>(s:string) => document.querySelector<T>(s)!;
const docs = new Map<string,FileDocument>(); let active:string|null=null; let job:string|null=null; let current:JobFinished|null=null; let poll:number|null=null; let lastOperation:Operation='format';
const rendererRegistry: Record<RendererKind, (text:string)=>string> = { text: text => text, tree: text => text, table: text => text, diff: text => text, binary: text => text, json: text => text };
const toolRegistry = new Map<string, ToolManifest>();
const implementedToolIds = new Set(['structured.json', 'structured.csv', 'text.inspect', 'encoding.hash', 'text.url', 'text.html', 'text.unicode']);
let activeToolId = 'structured.json';

let activeRenderer: RendererKind = 'json';
type Pending = { kind:'progress'|'finished'; event:JobProgress|JobFinished }; let pending:Pending[]=[];
const preview=$('#preview') as HTMLTextAreaElement, output=$('#result-output') as HTMLTextAreaElement|null, select=$('#format') as HTMLSelectElement, palette=$('#palette') as HTMLDialogElement, search=$('#palette-search') as HTMLInputElement, textOperation=$('#text-operation') as HTMLSelectElement;
const bytes=(v:number|null|undefined) => { if(typeof v!=='number'||!Number.isFinite(v)) return '—'; const u=['B','KB','MB','GB']; let n=v,i=0; while(n>=1024&&i<3){n/=1024;i++;} return (i===0||n>=100?n.toFixed(0):n.toFixed(1))+' '+u[i]; };
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]||c));
const setStatus=(s:string)=>$('#status').textContent=s;
const fail=(s:string)=>{ $('#error').textContent=s; $('#error').hidden=false; setStatus('Action failed'); };
const clearError=()=>{ $('#error').hidden=true; };

function renderTabs(){const root=$('#tabs');root.innerHTML=docs.size?'':'<span class="empty-tab">Your workspace</span>';docs.forEach(d=>{const b=document.createElement('button');b.className='tab '+(d.id===active?'active':'');b.role='tab';b.ariaSelected=String(d.id===active);b.title=d.path;b.innerHTML='<span class="file-dot '+d.format+'"></span><span class="tab-name">'+esc(d.name)+'</span><span class="tab-close" title="Close document" aria-label="Close document">×</span>';b.onclick=()=>{if(active===d.id)return;void switchDocument(d.id);};b.querySelector('.tab-close')?.addEventListener('click',e=>{e.stopPropagation();void closeTab(d.id);});root.append(b);});}
async function switchDocument(id:string){if(job){try{await cancelOperation(job);}catch{/* best effort */}job=null;if(poll!==null){clearInterval(poll);poll=null;}}active=id;current=null;clearError();render();renderTabs();setStatus('Document ready');}
async function closeTab(id:string){if(active===id&&job){try{await cancelOperation(job);}catch{/* best effort */}job=null;if(poll!==null){clearInterval(poll);poll=null;}}try{await closeDocument(id);}catch(e){fail(e instanceof Error?e.message:String(e));return;}docs.delete(id);if(active===id){active=docs.keys().next().value||null;current=null;}renderTabs();render();}
function render(){const d=active?docs.get(active):undefined,has=!!d;$('#empty-state').hidden=has;preview.hidden=!has;select.disabled=!has;['inspect','format-file','minify-file'].forEach(id=>$('#'+id).toggleAttribute('disabled',!has||!!job));if(!d){preview.value='';$('#preview-meta').textContent='Open a JSON, CSV, or text file';$('#source-name').textContent='No document open';$('#source-size').textContent='—';$('#source-format').textContent='—';$('#encoding').textContent='—';$('#result-empty').hidden=false;$('#result-content').hidden=true;return;}preview.value=d.preview;select.value=d.format;$('#preview-meta').textContent=(d.truncated?'First 64 KiB · ':'')+bytes(d.size)+' · '+d.format.toUpperCase();$('#preview-limit').textContent=d.truncated?'Preview limited to 64 KiB · Full-file processing':'Bounded preview · Full-file processing';$('#encoding').textContent=d.encoding+' · Read only';$('#source-name').textContent=d.name;$('#source-size').textContent=bytes(d.size);$('#source-format').textContent=d.format.toUpperCase();if(!current){$('#result-empty').hidden=false;$('#result-content').hidden=true;}}
async function openPath(p:string){clearError();if(!native){fail('The native Rust engine is unavailable in this browser preview. Open the desktop app to choose a file.');return;}try{if(job){try{await cancelOperation(job);}catch{/* best effort */}job=null;if(poll!==null){clearInterval(poll);poll=null;}}setStatus('Reading bounded preview…');const d=await openDocument(p);docs.set(d.id,d);active=d.id;current=null;renderTabs();render();setStatus('Loaded · formatting the complete file…');void run('format');}catch(e){fail(e instanceof Error?e.message:String(e));}}
async function openFile(){if(!native){fail('The native Rust engine is unavailable in this browser preview. Open the desktop app to choose a file.');return;}try{const p=await chooseFile();if(p)await openPath(p);}catch(e){fail(e instanceof Error?e.message:String(e));}}
async function run(op:Operation){const d=active?docs.get(active):undefined;if(!d||job)return;clearError();current=null;render();if(op!=='inspect'&&d.format!=='json'){fail('Formatting and minifying currently support JSON documents only.');return;}const toolId=d.format==='json'?'structured.json':d.format==='csv'?'structured.csv':'text.inspect';const registration=toolRegistry.get(toolId);if(!registration||!registration.operations.some(item=>item.id===op)){fail('This operation is unavailable for the selected document.');return;}activeToolId=toolId;activeRenderer=registration.renderer;try{await eventsReady;$('#job-panel').hidden=false;$('#job-title').textContent=op[0].toUpperCase()+op.slice(1)+' · '+d.name;$('#job-phase').textContent='Starting…';($('#job-progress') as HTMLProgressElement).value=0;setStatus(op[0].toUpperCase()+op.slice(1)+'ing complete file…');const s=await runTool(d.id,toolId,op,{});job=s.jobId;render();drain(s.jobId);if(job===s.jobId)startPoll(s.jobId);}catch(e){$('#job-panel').hidden=true;job=null;render();fail(e instanceof Error?e.message:String(e));}}
function progress(e:JobProgress){if(!job||e.jobId!==job){pending.push({kind:'progress',event:e});if(pending.length>48)pending=pending.slice(-48);return;}const p=e.totalBytes?Math.min(100,e.bytesProcessed/e.totalBytes*100):0;($('#job-progress') as HTMLProgressElement).value=p;$('#job-phase').textContent=e.phase;$('#job-bytes').textContent=bytes(e.bytesProcessed)+' of '+bytes(e.totalBytes);$('#job-percent').textContent=Math.round(p)+'%';}
async function runHash(algorithm:'sha256'|'sha512'){const d=active?docs.get(active):undefined;if(!d||job)return;clearError();current=null;render();try{await eventsReady;$('#job-panel').hidden=false;$('#job-title').textContent=algorithm.toUpperCase()+' · '+d.name;$('#job-phase').textContent='Starting…';($('#job-progress') as HTMLProgressElement).value=0;setStatus('Hashing complete file…');const s=await runTool(d.id,'encoding.hash',algorithm,{});job=s.jobId;render();drain(s.jobId);if(job===s.jobId)startPoll(s.jobId);}catch(e){$('#job-panel').hidden=true;job=null;render();fail(e instanceof Error?e.message:String(e));}}
function finished(e:JobFinished){if(!job||e.jobId!==job){pending.push({kind:'finished',event:e});if(pending.length>48)pending=pending.slice(-48);return;}void showFinished(e);}
async function showFinished(e:JobFinished){if(poll!==null){clearInterval(poll);poll=null;}job=null;current=e;render();$('#job-panel').hidden=true;const state=$('#result-state');state.className='result-state '+(e.ok?'ok':e.cancelled?'cancelled':'failed');state.textContent=e.ok?'✓ Completed successfully':e.cancelled?'○ Cancelled':'● '+(e.error||'Operation failed');const rows:Array<[string,string]>=[['Elapsed',e.elapsedMs+' ms'],['Input',bytes(e.inputBytes)]];if(typeof e.outputBytes==='number')rows.push(['Output',bytes(e.outputBytes)]);rows.push(['Status',e.ok?(e.resultDocumentId?'Ready to review':'Saved'):'No output']);$('#result-metrics').innerHTML=rows.map(r=>'<div><dt>'+r[0]+'</dt><dd>'+esc(r[1])+'</dd></div>').join('');$('#result-summary').textContent=typeof e.summary==='string'?e.summary:JSON.stringify(e.summary??{},null,2);$('#result-empty').hidden=true;$('#result-content').hidden=false;const save=$('#save-result') as HTMLButtonElement|null;if(save){save.hidden=!e.ok||!e.resultDocumentId;save.textContent=activeToolId==='encoding.hash'?'Save hash…':'Save formatted copy…';}const copy=document.querySelector("#copy-result") as HTMLButtonElement|null;if(copy)copy.hidden=!e.ok||!e.resultDocumentId;if(output)output.hidden=true;if(e.ok&&e.resultDocumentId&&output){try{const r=await readPreview(e.resultDocumentId,0);output.value=rendererRegistry[activeRenderer](r.preview);output.hidden=false;$('#result-output-meta').textContent=r.truncated?'Formatted preview · first 64 KiB':'Formatted output';}catch(x){fail(x instanceof Error?x.message:String(x));}}setStatus(e.ok?'Ready · result shown on the right':e.cancelled?'Cancelled':'Operation failed');}
function drain(id:string){const ev=pending.filter(x=>x.event.jobId===id);pending=pending.filter(x=>x.event.jobId!==id);ev.forEach(x=>x.kind==='progress'?progress(x.event as JobProgress):void showFinished(x.event as JobFinished));}
function startPoll(id:string){if(poll!==null)clearInterval(poll);poll=window.setInterval(()=>{if(job!==id)return;void jobStatus(id).then(r=>{if(r&&job===id)void showFinished(r);}).catch(()=>undefined);},180);}
async function saveCurrent(){const id=current?.resultDocumentId,d=active?docs.get(active):undefined;if(!id||!d)return;try{const path=await chooseOutput(d,activeToolId==='encoding.hash'?'hash':lastOperation);if(!path)return;await saveResult(id,path);$('#output-path').textContent=path;$('#saved-output').hidden=false;setStatus(activeToolId==='encoding.hash'?'Saved hash':'Saved formatted copy');}catch(e){fail(e instanceof Error?e.message:String(e));}}

type Command = { label:string; description:string; action:()=>void };
let commands:Command[]=[];
const iconFor=(m:ToolManifest)=>m.id.startsWith('structured.')?'{}':m.id.startsWith('encoding.')?'#':m.id.startsWith('text.')?'Aa':m.id.startsWith('web.')?'↗':m.renderer==='diff'?'⇄':'⌁';
const groupFor=(m:ToolManifest)=>m.id.startsWith('structured.')?'STRUCTURED DATA':m.id.startsWith('encoding.')||m.id.startsWith('text.')?'TEXT & ENCODING':m.id.startsWith('web.')?'WEB & API':m.renderer==='diff'?'COMPARE':'OTHER TOOLS';
const unavailable=(m:ToolManifest)=>fail(`${m.label} is currently unavailable in this desktop build.`);
function renderTextControls(){const textTool=activeToolId==='text.url'||activeToolId==='text.html'||activeToolId==='text.unicode';const hashTool=activeToolId==='encoding.hash';$('#text-operation-label').hidden=!textTool;textOperation.hidden=!textTool;textOperation.disabled=!active||!!job;$('#run-text').hidden=!textTool;($('#run-text') as HTMLButtonElement).disabled=!active||!!job;$('#hash-algorithm-label').hidden=!hashTool;$('#hash-algorithm').hidden=!hashTool;$('#run-hash').hidden=!hashTool;($('#run-hash') as HTMLButtonElement).disabled=!active||!!job;if(textTool){const m=toolRegistry.get(activeToolId);if(m)textOperation.innerHTML=m.operations.map(o=>`<option value="${esc(o.id)}">${esc(o.label)}</option>`).join('');}}
function runManifestCommand(m:ToolManifest,operationId:string){if(m.id==='encoding.hash'){activeToolId=m.id;render();void runHash(operationId as 'sha256'|'sha512');return;}if(!implementedToolIds.has(m.id)){unavailable(m);return;}if(m.id.startsWith('text.')&&m.id!=='text.inspect'){activeToolId=m.id;render();void runTextUtility(m.id as 'text.url'|'text.html'|'text.unicode',operationId);return;}if((m.id==='structured.json'&&(operationId==='inspect'||operationId==='format'||operationId==='minify'))||operationId==='inspect'){void run(operationId as Operation);return;}unavailable(m);}
async function runTextUtility(toolId:'text.url'|'text.html'|'text.unicode',operationId:string){const d=active?docs.get(active):undefined;if(!d||job)return;if(d.format!=='text'){fail('Text utilities require a text document.');return;}clearError();current=null;render();try{await eventsReady;$('#job-panel').hidden=false;$('#job-title').textContent=operationId[0].toUpperCase()+operationId.slice(1)+' · '+d.name;$('#job-phase').textContent='Starting…';($('#job-progress') as HTMLProgressElement).value=0;setStatus('Transforming complete file…');const s=await runTool(d.id,toolId,operationId,{});job=s.jobId;render();drain(s.jobId);if(job===s.jobId)startPoll(s.jobId);}catch(e){$('#job-panel').hidden=true;job=null;render();fail(e instanceof Error?e.message:String(e));}}
function renderTools(){const nav=$('.tool-nav');const query=toolSearch.value.trim().toLowerCase();const visible=[...toolRegistry.values()].filter(m=>!query||`${m.label} ${m.id}`.toLowerCase().includes(query));nav.innerHTML='';if(!visible.length){const empty=document.createElement('p');empty.className='search-empty';empty.textContent='No tools match your search.';nav.append(empty);return;}const groups=new Map<string,ToolManifest[]>();visible.forEach(m=>{const list=groups.get(groupFor(m))??[];list.push(m);groups.set(groupFor(m),list);});groups.forEach((items,group)=>{const section=document.createElement('div');section.className='tool-group';const label=document.createElement('div');label.className='group-label';label.textContent=group;section.append(label);items.forEach(m=>{const item=document.createElement('button');item.className='tool-item'+(m.id===activeToolId?' active':'');item.dataset.tool=m.id;item.title=implementedToolIds.has(m.id)?m.label:`${m.label} unavailable`;item.innerHTML=`<span class="tool-item-icon">${esc(iconFor(m))}</span><span><strong>${esc(m.label)}</strong><small>${esc(m.operations.map(o=>o.label).join(' · '))}</small></span>${m.id==='structured.json'?'<span class="tool-shortcut">1</span>':''}`;item.onclick=()=>{activeToolId=m.id;document.querySelectorAll('.tool-item').forEach(x=>x.classList.remove('active'));item.classList.add('active');$('#active-tool-label').textContent=m.label.toUpperCase();$('#active-tool-title').textContent=m.label;$('#active-tool-subtitle').textContent=implementedToolIds.has(m.id)?'Choose an operation from the toolbar or command palette.':'This tool is registered but unavailable in this build.';if(m.id==='encoding.hash'){render();}else if(!implementedToolIds.has(m.id))unavailable(m);};section.append(item);});nav.append(section);});}
function rebuildCommands(){commands=[{label:'Open file',description:'Choose a local document',action:()=>void openFile()}];toolRegistry.forEach(m=>m.operations.forEach(o=>{const label=m.id==='structured.json'&&o.id==='inspect'?'Inspect document':m.id==='structured.json'&&o.id==='format'?'Format JSON':m.id==='structured.json'&&o.id==='minify'?'Minify JSON':`${m.label}: ${o.label}`;commands.push({label,description:implementedToolIds.has(m.id)?`Run ${o.label.toLowerCase()} on the active document`:'Registered tool · unavailable in this build',action:()=>runManifestCommand(m,o.id)});}));}
function renderCommands(){paletteIndex=-1;const q=search.value.trim().toLowerCase();const shown=commands.filter(c=>`${c.label} ${c.description}`.toLowerCase().includes(q));$('#command-list').innerHTML=shown.length?shown.map((c,i)=>`<button data-i="${i}" role="option"><span class="command-glyph">⌁</span><span><strong>${esc(c.label)}</strong><small>${esc(c.description)}</small></span><kbd>↵</kbd></button>`).join(''):'<p class="search-empty">No commands match your search.</p>';const empty=document.querySelector('#palette-empty') as HTMLElement|null;if(empty)empty.hidden=shown.length>0;$('#command-list').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{palette.close();shown[Number(b.dataset.i)]?.action();});}
$('#open-file').onclick=()=>void openFile();$('#empty-open').onclick=()=>void openFile();$('#inspect').onclick=()=>void run('inspect');$('#format-file').onclick=()=>void run('format');$('#minify-file').onclick=()=>void run('minify');$('#run-hash').onclick=()=>void runHash(((document.querySelector('#hash-algorithm') as HTMLSelectElement).value||'sha256') as 'sha256'|'sha512');$('#save-result').onclick=()=>void saveCurrent();$('#copy-result').onclick=async()=>{const value=(document.querySelector('#result-output') as HTMLTextAreaElement).value;try{await navigator.clipboard.writeText(value);setStatus('Copied result to clipboard')}catch(e){fail('Could not copy result: '+String(e))}};$('#cancel-job').onclick=()=>{if(job)void cancelOperation(job).catch(e=>fail(String(e)));};$('#palette-open').onclick=()=>{renderCommands();palette.showModal();search.focus();};$('#palette-close').onclick=()=>palette.close();search.oninput=renderCommands;document.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();renderCommands();palette.showModal();search.focus();}if(e.key==='Escape'&&palette.open)palette.close();};
if(!native){$('#browser-notice').hidden=false;$('#engine-dot').classList.add('offline');$('#engine-status').textContent='Browser preview · native engine unavailable';setStatus('Preview only');}
const eventsReady=subscribeJobs(progress,finished).catch(e=>{if(native)fail('Could not connect to operation events: '+String(e));});renderTabs();render();








const toolSearch=$('#tool-search') as HTMLInputElement;
toolSearch.oninput=()=>renderTools();
async function loadToolRegistry(){
  try { const manifests=await listTools(); toolRegistry.clear(); manifests.forEach(m=>toolRegistry.set(m.id,m)); }
  catch(error){ if(native) fail('Could not load the tool registry: '+String(error)); }
  if(!toolRegistry.size) toolRegistry.set('structured.json',{id:'structured.json',label:'JSON',contractVersion:1,inputKinds:['json'],limits:{maxInputBytes:null,maxOutputBytes:null},capabilities:{deterministic:true,supportsPreview:true,supportsStreaming:true,cancellation:true,progress:true,needsFilesystem:true,needsNetwork:false,needsSecrets:false},operations:[{id:'inspect',label:'Inspect',defaultOptions:{}},{id:'format',label:'Format',defaultOptions:{}},{id:'minify',label:'Minify',defaultOptions:{}}],renderer:'json'});
  rebuildCommands(); renderTools(); renderCommands();
}
void loadToolRegistry();
$('#sidebar-collapse').onclick=()=>{$('.sidebar').classList.toggle('collapsed');};
const dropTarget=$('#document-panel');
dropTarget.addEventListener('dragover',e=>{e.preventDefault();dropTarget.classList.add('drag-over');});
dropTarget.addEventListener('dragleave',()=>dropTarget.classList.remove('drag-over'));
dropTarget.addEventListener('drop',e=>{e.preventDefault();dropTarget.classList.remove('drag-over');const file=e.dataTransfer?.files?.[0] as (File&{path?:string})|undefined;if(file?.path)void openPath(file.path);else fail('The dropped file path is unavailable in this preview. Use Open file instead.');});
let paletteIndex=-1;
function movePalette(delta:number){const items=[...document.querySelectorAll<HTMLButtonElement>('#command-list button')];if(!items.length)return;paletteIndex=(paletteIndex+delta+items.length)%items.length;items.forEach((item,i)=>item.classList.toggle('selected',i===paletteIndex));items[paletteIndex].focus();}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='o'){e.preventDefault();void openFile();return;}if(!palette.open)return;if(e.key==='ArrowDown'){e.preventDefault();movePalette(1);}else if(e.key==='ArrowUp'){e.preventDefault();movePalette(-1);}else if(e.key==='Enter'){e.preventDefault();const item=document.querySelector<HTMLButtonElement>('#command-list button.selected')??document.querySelector<HTMLButtonElement>('#command-list button');item?.click();}});
document.addEventListener('click',e=>{const id=(e.target as HTMLElement|null)?.id;if(id==='inspect')lastOperation='inspect';else if(id==='format-file')lastOperation='format';else if(id==='minify-file')lastOperation='minify';});
$('#run-text').onclick=()=>{if(activeToolId.startsWith('text.')){lastOperation=textOperation.value as Operation;void runTextUtility(activeToolId as 'text.url'|'text.html'|'text.unicode',textOperation.value);}};
textOperation.onchange=()=>{lastOperation=textOperation.value as Operation;};
document.addEventListener('click',e=>{const el=e.target as HTMLElement|null;if(el?.closest('.tool-item')){window.setTimeout(renderTextControls,0);}});









