"""Generate ../html-entities.mjs from the Python standard library entity tables.

The WHATWG HTML named character reference table (2231 names, including the 106
legacy names that decode without a trailing semicolon) is taken from
``html.entities.html5``. The preferred names used when escaping are the HTML 4.01
``codepoint2name`` table plus ``apos``. The C1 remap table is the WHATWG
numeric-character-reference-end table; every row is verified against
``html.unescape`` before it is written.

The output is ASCII only, sorted, and byte-for-byte reproducible:

    python plugins/escaping/scripts/generate-entities.py
"""

from __future__ import annotations

import hashlib
import html
import html.entities as entities
import json
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "html-entities.mjs"

C1_REMAP = {
    0x80: 0x20AC, 0x82: 0x201A, 0x83: 0x0192, 0x84: 0x201E, 0x85: 0x2026, 0x86: 0x2020,
    0x87: 0x2021, 0x88: 0x02C6, 0x89: 0x2030, 0x8A: 0x0160, 0x8B: 0x2039, 0x8C: 0x0152,
    0x8E: 0x017D, 0x91: 0x2018, 0x92: 0x2019, 0x93: 0x201C, 0x94: 0x201D, 0x95: 0x2022,
    0x96: 0x2013, 0x97: 0x2014, 0x98: 0x02DC, 0x99: 0x2122, 0x9A: 0x0161, 0x9B: 0x203A,
    0x9C: 0x0153, 0x9E: 0x017E, 0x9F: 0x0178,
}


def literal(text: str) -> str:
    """A JSON string literal is a valid ASCII-only JavaScript string literal."""
    return json.dumps(text, ensure_ascii=True)


def main() -> int:
    named = dict(sorted(entities.html5.items()))
    legacy = [name for name in named if not name.endswith(";")]
    for name in legacy:
        if named[name] != named[name + ";"]:
            raise SystemExit(f"legacy name {name} disagrees with {name};")
    # HTML 4.01 pointed &lang; and &rang; at U+2329/U+232A; HTML5 moved them to
    # U+27E8/U+27E9. Only names whose HTML5 meaning equals the HTML 4.01 code
    # point are preferred, so escaping never emits a name a browser reads differently.
    preferred: dict[int, str] = {
        codepoint: name for codepoint, name in entities.codepoint2name.items() if named.get(name + ";") == chr(codepoint)
    }
    dropped = sorted(set(entities.codepoint2name.values()) - set(preferred.values()))
    if dropped != ["lang", "rang"]:
        raise SystemExit(f"unexpected HTML 4.01/HTML5 disagreements: {dropped}")
    preferred[0x27] = "apos"
    for code, mapped in C1_REMAP.items():
        if html.unescape(f"&#{code};") != chr(mapped):
            raise SystemExit(f"C1 remap for 0x{code:02X} disagrees with html.unescape")
    for code in range(0x80, 0xA0):
        if code not in C1_REMAP and html.unescape(f"&#{code};") != chr(code):
            raise SystemExit(f"0x{code:02X} should not be remapped")

    canonical = json.dumps(list(named.items()), ensure_ascii=True, separators=(",", ":")).encode("ascii")
    table_hash = hashlib.sha256(canonical).hexdigest()

    lines = [
        "// Generated by scripts/generate-entities.py from the WHATWG HTML named character",
        "// reference table (Python html.entities). Do not edit by hand; regenerate instead.",
        "",
        "/** SHA-256 of the canonical JSON `[[name, text], ...]` list, sorted by name. */",
        f'export const TABLE_SHA256 = "{table_hash}";',
        "",
        "/** Longest legacy (semicolon-less) name; bounds the prefix search. */",
        f"export const LEGACY_MAX_LENGTH = {max(len(name) for name in legacy)};",
        "",
        "/** Longest name including its semicolon; bounds the alphanumeric run scan. */",
        f"export const NAME_MAX_LENGTH = {max(len(name) for name in named)};",
        "",
        "/** Numeric references 0x80-0x9F that HTML remaps to windows-1252 characters. */",
        "export const C1_REMAP = new Map([",
        *(f"  [0x{code:02X}, 0x{mapped:04X}]," for code, mapped in sorted(C1_REMAP.items())),
        "]);",
        "",
        "/** Names chosen when escaping with preferNamed: HTML 4.01 names plus apos. */",
        "export const PREFERRED_NAMES = new Map([",
        *(f"  [0x{codepoint:04X}, {literal(name)}]," for codepoint, name in sorted(preferred.items())),
        "]);",
        "",
        "/** Every WHATWG named reference. Keys keep their semicolon when the spec has one. */",
        "export const NAMED_REFERENCES = new Map([",
        *(f"  [{literal(name)}, {literal(text)}]," for name, text in named.items()),
        "]);",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"wrote {OUT} ({len(named)} names, {len(legacy)} legacy, {len(preferred)} preferred, sha256 {table_hash})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
