import { ProcessorCancelled } from "../../packages/plugin-sdk/src/index.ts";
const enc = new TextEncoder(); const dec = new TextDecoder("utf-8", {fatal:true});
const named = {amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:"\u00a0",copy:"\u00a9",reg:"\u00ae",hellip:"\u2026"};
const reverse = Object.fromEntries(Object.entries(named).map(([k,v])=>[v,k]));
function check(c){if(c.cancellation.isCancelled()) throw new ProcessorCancelled();}
async function input(c){const a=[];let n=0;for await(const x of c.readChunks("input",65536)){check(c);a.push(x);n+=x.byteLength;}try{return {text:dec.decode(Uint8Array.from(a.flatMap(x=>[...x])),{stream:false}),inputBytes:n};}catch{throw Error("input is not valid UTF-8 text");}}
function htmlEscape(s,o,c){let out="",i=0;for(const ch of s){if((i++&4095)===0)check(c);const cp=ch.codePointAt(0);const unsafe=o.encodeEverything||/[&<>"']/.test(ch)||cp<0x20||cp>0x7e;if(!unsafe){out+=ch;continue;}if(o.preferNamed&&reverse[ch])out+=`&${reverse[ch]};`;else out+=`&#${o.numeric==="hex"?"x"+cp.toString(16).toUpperCase():cp};`;}return out;}
function htmlUnescape(s,o,c){return s.replace(/&(?:#([0-9]+)|#x([0-9a-f]+)|([A-Za-z][A-Za-z0-9]+));/giu,(whole,d,h,name,offset)=>{check(c);let ch;if(name)ch=named[name.toLowerCase()];else {const cp=Number.parseInt(d??h,h?16:10);ch=Number.isFinite(cp)&&cp>=0&&cp<=0x10ffff?String.fromCodePoint(cp):undefined;}if(!ch||!/^[$\u0000-\u{10ffff}]$/u.test(ch)) {if(o.strict)throw Error(`invalid HTML entity at UTF-16 offset ${offset}`);return whole;}return ch;});}
function backEscape(s,o,c){let out="",i=0;for(const ch of s){if((i++&4095)===0)check(c);const cp=ch.codePointAt(0);if(ch==='\\')out+='\\\\';else if(ch==='\n')out+='\\n';else if(ch==='\r')out+='\\r';else if(ch==='\t')out+='\\t';else if(ch==='\b')out+='\\b';else if(ch==='\f')out+='\\f';else if(ch==='"')out+='\\"';else if(ch==="'")out+="\\'";else if(cp<0x20||(!o.unicode&&cp>0x7e))out+='\\u'+cp.toString(16).padStart(4,'0');else if(o.unicode&&cp>0x7e)out+='\\u{'+cp.toString(16).toUpperCase()+'}';else out+=ch;}return out;}
function backUnescape(s,o,c){let out="";for(let i=0;i<s.length;i++){if((i&4095)===0)check(c);if(s[i]!=='\\'){out+=s[i];continue;}const at=i++;if(i>=s.length)throw Error(`incomplete escape at UTF-16 offset ${at}`);const k=s[i++];const map={n:'\n',r:'\r',t:'\t',b:'\b',f:'\f',v:'\v','0':'\0','\\':'\\','"':'"',"'":"'"};if(k in map){out+=map[k];continue;}if(k==='x'){const h=s.slice(i,i+2);if(!/^[0-9a-f]{2}$/iu.test(h))throw Error(`\\x escape requires two hexadecimal digits at UTF-16 offset ${at}`);out+=String.fromCharCode(parseInt(h,16));i+=2;continue;}if(k==='u'){let h;if(s[i]==='{'){const end=s.indexOf('}',i+1);if(end<0)throw Error(`Unicode escape is incomplete at UTF-16 offset ${at}`);h=s.slice(i+1,end);i=end+1;if(!/^[0-9a-f]{1,6}$/iu.test(h))throw Error(`invalid Unicode escape at UTF-16 offset ${at}`);}else{h=s.slice(i,i+4);if(!/^[0-9a-f]{4}$/iu.test(h))throw Error(`Unicode escape requires four hexadecimal digits at UTF-16 offset ${at}`);i+=4;}const cp=parseInt(h,16);if(cp>0x10ffff||(cp>=0xd800&&cp<=0xdfff))throw Error(`Unicode escape is not a scalar at UTF-16 offset ${at}`);out+=String.fromCodePoint(cp);continue;}throw Error(`unknown escape \\${k} at UTF-16 offset ${at}`);}return out;}
async function emit(c,text,meta){const bytes=enc.encode(text);if(bytes.byteLength>c.limits.maxOutputBytes)throw Error(`output exceeds ${c.limits.maxOutputBytes} bytes`);await c.writeValue("output",{...meta,text,outputBytes:bytes.byteLength,complete:true});await c.write("output",bytes);return text;}
export async function execute(req,c){const {text,inputBytes}=await input(c);const o=req?.options??{}, mode=o.mode??"escape";let out;
if(req.operationId==="text.html"){if(mode!=="escape"&&mode!=="unescape")throw Error("mode must be escape or unescape");out=mode==="escape"?htmlEscape(text,{numeric:o.numeric??"decimal",preferNamed:o.preferNamed!==false,encodeEverything:o.encodeEverything===true},c):htmlUnescape(text,{strict:o.strict!==false},c);}
else if(req.operationId==="text.json-string"){if(mode==="escape")out=JSON.stringify(text);else if(mode==="unescape"){try{const v=JSON.parse(text);if(typeof v!=="string")throw Error("JSON value must be a string");out=v;}catch(e){throw Error(`malformed JSON string: ${e.message}`);}}else throw Error("mode must be escape or unescape");}
else if(req.operationId==="text.backslash"){if(mode!=="escape"&&mode!=="unescape")throw Error("mode must be escape or unescape");out=mode==="escape"?backEscape(text,{unicode:o.unicode!==false},c):backUnescape(text,o,c);}
else throw Error(`unsupported operation ${req?.operationId}`);
return emit(c,out,{operationId:req.operationId,mode,inputBytes});}
