import { readdir, readFile, stat, realpath } from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import type { PluginManifest } from "../../plugin-contract/ts/generated.ts";
import { validateManifest } from "../../plugin-contract/ts/validate.ts";

export interface PackageDescriptor { apiVersion: string; manifest: string; processor: string; frontend?: string; }
export interface DiscoveredPackage { root: string; descriptor: PackageDescriptor; manifestPath: string; processorPath: string; frontendPath?: string; manifest: PluginManifest; }
export class DiscoveryDiagnostic extends Error { readonly code: string; readonly plugin?: string; constructor(code: string, message: string, plugin?: string) { super(`${code}${plugin ? ` [${plugin}]` : ""}: ${message}`); this.code = code; this.plugin = plugin; } }
const API = "devtools.plugin/v2";
async function entrypoint(root: string, plugin: string, field: string, value: string): Promise<string> { if (!value.trim() || isAbsolute(value) || value.split(/[\\/]/u).includes("..")) throw new DiscoveryDiagnostic("invalid-entrypoint", "entrypoint must be a non-empty relative path without traversal", plugin); const candidate = resolve(root, value); const rel = relative(root, candidate); if (rel.startsWith(`..${sep}`) || isAbsolute(rel)) throw new DiscoveryDiagnostic("path-traversal", "entrypoint escapes package root", plugin); const realRoot = await realpath(root); const real = await realpath(candidate).catch(() => { throw new DiscoveryDiagnostic("missing-entrypoint", `${field} entrypoint does not exist`, plugin); }); if (real !== realRoot && !real.startsWith(`${realRoot}${sep}`)) throw new DiscoveryDiagnostic("path-traversal", "entrypoint resolves outside package root", plugin); if (!(await stat(real)).isFile()) throw new DiscoveryDiagnostic("malformed-entrypoint", `${field} entrypoint is not a file`, plugin); return real; }
export async function discoverPlugins(root: string): Promise<DiscoveredPackage[]> { const absolute = resolve(root); let dirs; try { dirs = (await readdir(absolute, { withFileTypes: true })).filter((entry) => entry.isDirectory()).sort((a, b) => a.name.localeCompare(b.name)); } catch { throw new DiscoveryDiagnostic("missing-root", `trusted plugin root does not exist: ${absolute}`); } const result: DiscoveredPackage[] = []; for (const dir of dirs) { const packageRoot = join(absolute, dir.name); const descriptorPath = join(packageRoot, "plugin.json"); let descriptor: PackageDescriptor; try { descriptor = JSON.parse(await readFile(descriptorPath, "utf8")) as PackageDescriptor; } catch (error) { throw new DiscoveryDiagnostic("invalid-descriptor", error instanceof Error ? error.message : String(error), dir.name); } if (descriptor.apiVersion !== API) throw new DiscoveryDiagnostic("unsupported-api", `expected ${API}, got ${descriptor.apiVersion ?? "missing"}`, dir.name); if (!descriptor.processor?.trim()) throw new DiscoveryDiagnostic("missing-processor", "processor entrypoint is required", dir.name); const manifestPath = await entrypoint(packageRoot, dir.name, "manifest", descriptor.manifest); const processorPath = await entrypoint(packageRoot, dir.name, "processor", descriptor.processor); const frontendPath = descriptor.frontend ? await entrypoint(packageRoot, dir.name, "frontend", descriptor.frontend) : undefined; let manifest: PluginManifest; try { manifest = validateManifest(JSON.parse(await readFile(manifestPath, "utf8"))); } catch (error) { throw new DiscoveryDiagnostic("invalid-manifest", error instanceof Error ? error.message : String(error), dir.name); } result.push({ root: packageRoot, descriptor, manifestPath, processorPath, frontendPath, manifest }); } result.sort((a, b) => a.manifest.id.localeCompare(b.manifest.id) || a.root.localeCompare(b.root)); for (let i = 1; i < result.length; i++) if (result[i - 1].manifest.id === result[i].manifest.id) throw new DiscoveryDiagnostic("duplicate-id", `duplicate plugin id in ${result[i - 1].root} and ${result[i].root}`, result[i].manifest.id); return result; }
