import { ProcessorCancelled } from "../../packages/plugin-sdk/src/index.ts";
const enc=new TextEncoder(), dec=new TextDecoder("utf-8",{fatal:true}); const MAX_TEXT=1024*1024, MAX_MATCHES=10000;
function check(c){if(c.cancellation.isCancelled())throw new ProcessorCancelled();}
async function read(c){const chunks=[];let n=0;for await(const x of c.readChunks("input",65536)){check(c);n+=x.byteLength;if(n>c.limits.maxInputBytes)throw Error(`input exceeds ${c.limits.maxInputBytes} bytes`);chunks.push(x);}let bytes=new Uint8Array(n),at=0;for(const x of chunks){bytes.set(x,at);at+=x.byteLength;}try{return {text:dec.decode(bytes),inputBytes:n};}catch{throw Error("input is not valid UTF-8 text");}}
function esc(s){return s.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
function word(s,i,j){const cp=(p)=>p<0||p>=s.length?undefined:Array.from(s.slice(p))[0];const a=cp(i-1),b=cp(j);return !(a&&/^[\p{L}\p{N}\p{M}_]$/u.test(a))&&!(b&&/^[\p{L}\p{N}\p{M}_]$/u.test(b));}
function matches(text,q,o,c){if(text.length>MAX_TEXT)throw Error(`find and replace is limited to ${MAX_TEXT} UTF-16 code units`);if(!q)return {items:[],truncated:false};const re=new RegExp(esc(q),o.caseSensitive===false?"giu":"gu"),items=[];let m,truncated=false;while((m=re.exec(text))!==null){check(c);const start=m.index,end=start+m[0].length;if(o.wholeWord&&!word(text,start,end))continue;if(items.length<MAX_MATCHES)items.push({start,end,match:m[0]});else{truncated=true;break;}}return {items,truncated};}
async function emit(c,value){const text=JSON.stringify(value,null,2),bytes=enc.encode(text);if(bytes.byteLength>c.limits.maxOutputBytes)throw Error(`output exceeds ${c.limits.maxOutputBytes} bytes`);await c.writeValue("output",value);await c.write("output",bytes);return value;}
export async function execute(req,c){const {text,inputBytes}=await read(c);const o=req?.options??{},query=String(o.query??""),replacement=String(o.replacement??""),mode=o.mode??"find";if(mode!=="find"&&mode!=="replace"&&mode!=="replaceAll")throw Error("mode must be find, replace, or replaceAll");const found=matches(text,query,{caseSensitive:o.caseSensitive!==false,wholeWord:o.wholeWord===true},c);let output=text,count=mode==="find"?found.items.length:0;if(mode==="replace"&&found.items.length){const m=found.items[0];output=text.slice(0,m.start)+replacement+text.slice(m.end);count=1;}else if(mode==="replaceAll"&&found.items.length){let cursor=0;const p=[];for(const m of found.items){p.push(text.slice(cursor,m.start),replacement);cursor=m.end;}p.push(text.slice(cursor));output=p.join("");count=found.items.length;}if(output.length>MAX_TEXT)throw Error(`replacement would exceed ${MAX_TEXT} UTF-16 code units`);return emit(c,{mode,query,replacement,matches:found.items,count,truncated:found.truncated,text:output,inputBytes,outputBytes:enc.encode(output).byteLength,complete:true});}
