// @generated by scripts/generate.mjs from schema/contract.v2.schema.json. DO NOT EDIT.

export type ApiVersion = "devtools.plugin/v2";

export type Identifier = string;

export type ChoiceIdentifier = string;

export type DecimalInteger = string;

export type UnsignedDecimal = string;

export type DecimalValue = string;

export type JsonObject = Record<string, unknown>;

export type StringMap = Record<string, string>;

export type DecimalMap = Record<string, UnsignedDecimal>;

export interface PluginManifest { "kind": "pluginManifest"; "apiVersion": ApiVersion; "id": Identifier; "version": string; "stateVersion": number; "title"?: string; "description"?: string; "aliases"?: Array<AliasSpec>; "tools": Array<ToolSpec>; "operations": Array<OperationSpec>; "workspaces": Array<WorkspaceSpec>; "capabilities": Array<CapabilityRequest>; "settings": Array<OptionSpec>; "detection"?: DetectionSpec; "tests": TestDeclaration; "extensions"?: JsonObject; }

export interface AliasSpec { "id": Identifier; "toolId": Identifier; }

export interface ToolSpec { "id": Identifier; "title": string; "category": string; "description"?: string; "searchAliases"?: Array<string>; "icon"?: string; "operationIds": Array<Identifier>; "workspaceId": Identifier; "sampleIds"?: Array<Identifier>; "extensions"?: JsonObject; }

export interface OperationSpec { "id": Identifier; "title": string; "executor": ExecutorSpec; "inputs": Array<InputPortSpec>; "outputs": Array<OutputPortSpec>; "options": Array<OptionSpec>; "trigger": TriggerPolicy; "limits": LimitPolicy; "cache"?: CachePolicy; "extensions"?: JsonObject; }

export interface ExecutorSpec { "kind": "rust" | "javascriptWorker"; "id": Identifier; "version": string; "engine"?: string; "engineVersion"?: string; "syntax"?: string; "cancellation": "cooperative" | "enforced"; }

export type PortMultiplicity = "one" | "many";

export type InputPortKind = "document" | "value" | "selection" | "secret" | "file" | "image";

export type OutputPortKind = "artifact" | "value" | "report";

export interface InputPortSpec { "id": Identifier; "label"?: string; "kind": InputPortKind; "required": boolean; "multiplicity": PortMultiplicity; "contentKinds"?: Array<"text" | "image" | "binary" | "table" | "scalar">; "mime"?: Array<string>; "languages"?: Array<string>; "maxBytes"?: UnsignedDecimal; "sensitive"?: boolean; "extensions"?: JsonObject; }

export interface OutputPortSpec { "id": Identifier; "label"?: string; "kind": OutputPortKind; "multiplicity": PortMultiplicity; "mime"?: Array<string>; "language"?: string; "representations": Array<RepresentationKind>; "sensitive": boolean; "exports": Array<ExportKind>; "extensions"?: JsonObject; }

export type RepresentationKind = "text" | "code" | "image" | "table" | "tree" | "diff" | "properties" | "annotations" | "previewDocument" | "status";

export type ExportKind = "copyText" | "copyImage" | "copyHtml" | "save" | "useAsInput" | "openAsTab" | "openInBrowser";

export type CommonOptionFields = Record<string, never>;

export type OptionSpec = BooleanOption | StringOption | IntegerOption | DecimalOption | EnumOption | ListOption | RecordOption | TaggedUnionOption | DocumentOption | SecretOption | ResourceOption;

export interface BooleanOption { "id": Identifier; "type": "boolean"; "label": string; "default": boolean; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export interface StringOption { "id": Identifier; "type": "string"; "label": string; "default": string; "minLength"?: UnsignedDecimal; "maxLength"?: UnsignedDecimal; "pattern"?: string; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export interface IntegerOption { "id": Identifier; "type": "integer"; "label": string; "default": DecimalInteger; "minimum"?: DecimalInteger; "maximum"?: DecimalInteger; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export interface DecimalOption { "id": Identifier; "type": "decimal"; "label": string; "default": DecimalValue; "minimum"?: DecimalValue; "maximum"?: DecimalValue; "scale"?: UnsignedDecimal; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export interface EnumChoice { "id": ChoiceIdentifier; "label": string; }

export interface EnumOption { "id": Identifier; "type": "enum"; "label": string; "default": ChoiceIdentifier; "choices": Array<EnumChoice>; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export interface ValueShape { "type": "boolean" | "string" | "integer" | "decimal" | "object"; "sensitive"?: boolean; }

export interface ListOption { "id": Identifier; "type": "list"; "label": string; "default": Array<unknown>; "items": ValueShape; "minItems"?: UnsignedDecimal; "maxItems"?: UnsignedDecimal; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export interface RecordOption { "id": Identifier; "type": "record"; "label": string; "default": JsonObject; "fields": Array<OptionSpec>; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export interface TaggedVariant { "tag": Identifier; "label": string; "fields": Array<OptionSpec>; }

export interface TaggedUnionOption { "id": Identifier; "type": "taggedUnion"; "label": string; "default": JsonObject; "variants": Array<TaggedVariant>; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export interface DocumentOption { "id": Identifier; "type": "document"; "label": string; "languages": Array<string>; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export interface SecretOption { "id": Identifier; "type": "secret"; "label": string; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export interface ResourceOption { "id": Identifier; "type": "resource"; "label": string; "resourceKind": "file" | "image"; "mime"?: Array<string>; "persistence": Persistence; "sensitive": boolean; "group"?: string; "advanced"?: boolean; "rules"?: ConditionalRules; }

export type Persistence = "workspace" | "instance" | "session" | "none";

export type ConditionalRules = Array<ConditionalRule>;

export interface ConditionalRule { "effect": "visible" | "required" | "enabled"; "when": Condition; }

export type Condition = PredicateCondition | AllCondition | AnyCondition | NotCondition;

export interface PredicateCondition { "kind": "predicate"; "optionId": Identifier; "operator": "equals" | "notEquals" | "in" | "isSet"; "value"?: unknown; }

export interface AllCondition { "kind": "all"; "conditions": Array<Condition>; }

export interface AnyCondition { "kind": "any"; "conditions": Array<Condition>; }

export interface NotCondition { "kind": "not"; "condition": Condition; }

export interface TriggerPolicy { "modes": Array<"explicit" | "inputChange" | "selectionChange" | "heldRepeat">; "debounceMs": UnsignedDecimal; "changedPorts"?: Array<Identifier>; }

export interface LimitPolicy { "maxInputBytes": UnsignedDecimal; "maxOutputBytes": UnsignedDecimal; "maxChunkBytes": UnsignedDecimal; "deadlineMs": UnsignedDecimal; "maxRows"?: UnsignedDecimal; "maxNodes"?: UnsignedDecimal; "maxAnnotations"?: UnsignedDecimal; "maxPixels"?: UnsignedDecimal; "maxPreviewBytes"?: UnsignedDecimal; }

export interface CachePolicy { "mode": "deterministic" | "capturedContext" | "disabled"; "varyBy"?: Array<"inputRevisions" | "options" | "pluginVersion" | "engineVersion" | "locale" | "timezone" | "clock" | "randomness">; }

export type CapabilityId = "clipboard.readText" | "clipboard.readImage" | "clipboard.readHtml" | "clipboard.writeText" | "clipboard.writeImage" | "clipboard.writeHtml" | "documents.read" | "documents.readRange" | "documents.create" | "artifacts.write" | "files.import" | "files.export" | "secrets.use" | "clock.capture" | "randomness.seeded" | "preview.scripts" | "preview.network" | "preview.navigation" | "preview.localResources" | "preview.externalBrowser";

export interface CapabilityRequest { "id": CapabilityId; "required": boolean; "reason"?: string; "policy"?: JsonObject; }

export type WorkspaceKind = "singleEditor" | "transform" | "annotatedEditor" | "linkedFields" | "compare" | "generator" | "mediaPreview";

export interface WorkspaceSpec { "id": Identifier; "kind": WorkspaceKind; "bindings": Array<WorkspaceBinding>; "commands": Array<CommandSpec>; "presentationSettings": Array<PresentationSetting>; "trustedView"?: string; "extensions"?: JsonObject; }

export interface WorkspaceBinding { "id": Identifier; "component": "editor" | "field" | "form" | "output" | "diagnostics" | "properties" | "table" | "tree" | "diff" | "image" | "preview" | "annotations" | "status"; "inputPort"?: Identifier; "outputPort"?: Identifier; "optionIds"?: Array<Identifier>; "commandIds"?: Array<Identifier>; "selectionSource"?: Identifier; }

export interface CommandSpec { "id": Identifier; "label": string; "intent": "run" | "copy" | "save" | "clear" | "sample" | "open" | "paste" | "swap" | "cancel" | "navigate" | "openBrowser"; "operationId"?: Identifier; "inputPort"?: Identifier; "outputPort"?: Identifier; "semanticBinding"?: string; }

export interface PresentationSetting { "id": Identifier; "type": "boolean" | "enum" | "splitRatio" | "view"; "label": string; "default": unknown; "choices"?: Array<EnumChoice>; "persist"?: boolean; }

export interface DetectionSpec { "mode": "disabled" | "suggest" | "autoNewTab"; "maxProbeBytes": UnsignedDecimal; "probeExecutor"?: Identifier; }

export interface TestDeclaration { "requirementIds": Array<string>; "fixtures": Array<string>; "uiScenarios": Array<string>; }

export interface ExecuteRequest { "kind": "executeRequest"; "apiVersion": ApiVersion; "pluginId": Identifier; "pluginVersion": string; "toolId": Identifier; "operationId": Identifier; "instanceId": string; "jobId": string; "generation": UnsignedDecimal; "inputs": Record<string, InputBindingValue>; "options": JsonObject; "trigger": Trigger; "context": ExecutionContext; "requestedLimits": RequestedLimits; }

export type InputBinding = DocumentRef | ValueRef | SelectionRef | SecretRef | ResourceRef;

export type InputBindingValue = InputBinding | Array<InputBinding>;

export interface DocumentRef { "kind": "document"; "id": string; "revision": UnsignedDecimal; "byteLength": UnsignedDecimal; "contentKind": "text" | "image" | "binary" | "table" | "scalar"; "mime"?: string; "language"?: string; "encoding": "utf8" | "utf16Le" | "utf16Be" | "latin1" | "binary"; "newline": "lf" | "crLf" | "cr" | "mixed" | "none" | "unknown"; }

export interface ValueRef { "kind": "value"; "value": unknown; "sensitive"?: boolean; }

export interface SelectionRef { "kind": "selection"; "documentId": string; "revision": UnsignedDecimal; "selectionEpoch": UnsignedDecimal; "startByte": UnsignedDecimal; "endByte": UnsignedDecimal; }

export interface SecretRef { "kind": "secret"; "handle": string; }

export interface ResourceRef { "kind": "file" | "image"; "handle": string; "byteLength": UnsignedDecimal; "mime"?: string; }

export interface Trigger { "kind": "explicit" | "inputChange" | "selectionChange" | "heldRepeat"; "changedPort"?: Identifier; "origin": Origin; "revisionVector": DecimalMap; }

export interface Origin { "kind": "userEdit" | "derived" | "file" | "clipboard" | "dragDrop" | "generated" | "command"; "sourceId"?: string; "parentJobId"?: string; }

export interface ExecutionContext { "locale": string; "timezone": string; "capturedClock"?: string; "randomnessHandle"?: string; }

export interface RequestedLimits { "maxOutputBytes"?: UnsignedDecimal; "deadlineMs"?: UnsignedDecimal; "maxPreviewBytes"?: UnsignedDecimal; }

export interface EventIdentity { "apiVersion": ApiVersion; "pluginId": Identifier; "pluginVersion": string; "toolId": Identifier; "operationId": Identifier; "instanceId": string; "jobId": string; "generation": UnsignedDecimal; "sequence": UnsignedDecimal; }

export type JobEvent = AcceptedEvent | QueuedEvent | RunningEvent | ProgressEvent | OutputEvent | DiagnosticEvent | CompletedEvent | FailedEvent | CancelledEvent | CancelAcknowledgedEvent;

export interface AcceptedEvent { "kind": "accepted"; "identity": EventIdentity; }

export interface QueuedEvent { "kind": "queued"; "identity": EventIdentity; }

export interface RunningEvent { "kind": "running"; "identity": EventIdentity; }

export interface ProgressEvent { "kind": "progress"; "identity": EventIdentity; "phase": string; "processed": UnsignedDecimal; "total"?: UnsignedDecimal; }

export interface OutputEvent { "kind": "output"; "identity": EventIdentity; "portId": Identifier; "output": OutputDescriptor; }

export interface DiagnosticEvent { "kind": "diagnostic"; "identity": EventIdentity; "diagnostic": Diagnostic; }

export interface CompletedEvent { "kind": "completed"; "identity": EventIdentity; "outputs": Record<string, OutputDescriptor>; "diagnostics": Array<Diagnostic>; "stats": Stats; "provenance": Provenance; }

export interface FailedEvent { "kind": "failed"; "identity": EventIdentity; "error": ContractError; "diagnostics": Array<Diagnostic>; }

export interface CancelledEvent { "kind": "cancelled"; "identity": EventIdentity; "reason": "user" | "superseded" | "resourceLimit" | "shutdown" | "timeout"; "cleanupComplete": boolean; }

export interface CancelAcknowledgedEvent { "kind": "cancelAcknowledged"; "identity": EventIdentity; }

export interface OutputDescriptor { "representation": RepresentationKind; "artifactRef"?: ArtifactRef; "boundedValue"?: unknown; "language"?: string; "mime"?: string; "complete": boolean; "preview"?: PreviewDescriptor; "availableViews": Array<RepresentationKind>; "exportFormats": Array<ExportKind>; "sensitive": boolean; }

export interface ArtifactRef { "handle": string; "byteLength": UnsignedDecimal; "contentHash": string; }

export interface PreviewDescriptor { "truncated": boolean; "offset": UnsignedDecimal; "byteLength": UnsignedDecimal; }

export interface Diagnostic { "code": Identifier; "severity": "hint" | "info" | "warning" | "error"; "message": string; "source"?: SourceSpan; "related"?: Array<SourceSpan>; "data"?: JsonObject; }

export interface SourceSpan { "documentId": string; "revision": UnsignedDecimal; "startByte": UnsignedDecimal; "endByte": UnsignedDecimal; }

export interface Stats { "elapsedMs": UnsignedDecimal; "inputBytes": UnsignedDecimal; "outputBytes": UnsignedDecimal; "rows"?: UnsignedDecimal; "annotations"?: UnsignedDecimal; }

export interface Provenance { "pluginId": Identifier; "pluginVersion": string; "operationId": Identifier; "engine": string; "engineVersion": string; "syntax"?: string; "inputRevisions": DecimalMap; "optionsDigest": string; "capturedClock"?: string; "randomnessId"?: string; }

export interface ContractError { "code": Identifier; "message": string; "retryable"?: boolean; "details"?: JsonObject; }

export type ContractDocument = PluginManifest | ExecuteRequest | JobEvent;

export const CONTRACT_SCHEMA = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://thedevtools.pro/schemas/plugin-contract/v2",
  "title": "DevTools Plugin Contract v2",
  "description": "Canonical wire contract for bundled plugins. JSON numbers are never used for byte lengths, revisions, generations, offsets, counts, or arbitrary-precision integers.",
  "oneOf": [
    {
      "$ref": "#/$defs/PluginManifest"
    },
    {
      "$ref": "#/$defs/ExecuteRequest"
    },
    {
      "$ref": "#/$defs/JobEvent"
    }
  ],
  "$defs": {
    "ApiVersion": {
      "type": "string",
      "const": "devtools.plugin/v2"
    },
    "Identifier": {
      "type": "string",
      "pattern": "^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$",
      "minLength": 1,
      "maxLength": 128
    },
    "ChoiceIdentifier": {
      "type": "string",
      "pattern": "^[A-Za-z][A-Za-z0-9]*(?:[._-][A-Za-z0-9]+)*$",
      "minLength": 1,
      "maxLength": 128
    },
    "DecimalInteger": {
      "type": "string",
      "pattern": "^(?:0|-?[1-9][0-9]*)$"
    },
    "UnsignedDecimal": {
      "type": "string",
      "pattern": "^(?:0|[1-9][0-9]*)$"
    },
    "DecimalValue": {
      "type": "string",
      "pattern": "^-?(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?$"
    },
    "JsonObject": {
      "type": "object",
      "additionalProperties": true
    },
    "StringMap": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "DecimalMap": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/UnsignedDecimal"
      }
    },
    "PluginManifest": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "apiVersion",
        "id",
        "version",
        "stateVersion",
        "tools",
        "operations",
        "workspaces",
        "capabilities",
        "settings",
        "tests"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "pluginManifest"
        },
        "apiVersion": {
          "$ref": "#/$defs/ApiVersion"
        },
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "version": {
          "type": "string",
          "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+(?:[-+][0-9A-Za-z.-]+)?$"
        },
        "stateVersion": {
          "type": "integer",
          "minimum": 0,
          "maximum": 4294967295
        },
        "title": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string"
        },
        "aliases": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/AliasSpec"
          },
          "default": []
        },
        "tools": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/ToolSpec"
          }
        },
        "operations": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/OperationSpec"
          }
        },
        "workspaces": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/WorkspaceSpec"
          }
        },
        "capabilities": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CapabilityRequest"
          }
        },
        "settings": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/OptionSpec"
          }
        },
        "detection": {
          "$ref": "#/$defs/DetectionSpec"
        },
        "tests": {
          "$ref": "#/$defs/TestDeclaration"
        },
        "extensions": {
          "$ref": "#/$defs/JsonObject"
        }
      }
    },
    "AliasSpec": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "toolId"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "toolId": {
          "$ref": "#/$defs/Identifier"
        }
      }
    },
    "ToolSpec": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "title",
        "category",
        "operationIds",
        "workspaceId"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "title": {
          "type": "string",
          "minLength": 1
        },
        "category": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string"
        },
        "searchAliases": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "icon": {
          "type": "string"
        },
        "operationIds": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/Identifier"
          }
        },
        "workspaceId": {
          "$ref": "#/$defs/Identifier"
        },
        "sampleIds": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Identifier"
          }
        },
        "extensions": {
          "$ref": "#/$defs/JsonObject"
        }
      }
    },
    "OperationSpec": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "title",
        "executor",
        "inputs",
        "outputs",
        "options",
        "trigger",
        "limits"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "title": {
          "type": "string",
          "minLength": 1
        },
        "executor": {
          "$ref": "#/$defs/ExecutorSpec"
        },
        "inputs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/InputPortSpec"
          }
        },
        "outputs": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/OutputPortSpec"
          }
        },
        "options": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/OptionSpec"
          }
        },
        "trigger": {
          "$ref": "#/$defs/TriggerPolicy"
        },
        "limits": {
          "$ref": "#/$defs/LimitPolicy"
        },
        "cache": {
          "$ref": "#/$defs/CachePolicy"
        },
        "extensions": {
          "$ref": "#/$defs/JsonObject"
        }
      }
    },
    "ExecutorSpec": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "id",
        "version",
        "cancellation"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "rust",
            "javascriptWorker"
          ]
        },
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "version": {
          "type": "string",
          "minLength": 1
        },
        "engine": {
          "type": "string"
        },
        "engineVersion": {
          "type": "string"
        },
        "syntax": {
          "type": "string"
        },
        "cancellation": {
          "type": "string",
          "enum": [
            "cooperative",
            "enforced"
          ]
        }
      }
    },
    "PortMultiplicity": {
      "type": "string",
      "enum": [
        "one",
        "many"
      ]
    },
    "InputPortKind": {
      "type": "string",
      "enum": [
        "document",
        "value",
        "selection",
        "secret",
        "file",
        "image"
      ]
    },
    "OutputPortKind": {
      "type": "string",
      "enum": [
        "artifact",
        "value",
        "report"
      ]
    },
    "InputPortSpec": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "kind",
        "required",
        "multiplicity"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "label": {
          "type": "string"
        },
        "kind": {
          "$ref": "#/$defs/InputPortKind"
        },
        "required": {
          "type": "boolean"
        },
        "multiplicity": {
          "$ref": "#/$defs/PortMultiplicity"
        },
        "contentKinds": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "text",
              "image",
              "binary",
              "table",
              "scalar"
            ]
          }
        },
        "mime": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "languages": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "maxBytes": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "sensitive": {
          "type": "boolean",
          "default": false
        },
        "extensions": {
          "$ref": "#/$defs/JsonObject"
        }
      }
    },
    "OutputPortSpec": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "kind",
        "multiplicity",
        "representations",
        "sensitive",
        "exports"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "label": {
          "type": "string"
        },
        "kind": {
          "$ref": "#/$defs/OutputPortKind"
        },
        "multiplicity": {
          "$ref": "#/$defs/PortMultiplicity"
        },
        "mime": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "language": {
          "type": "string"
        },
        "representations": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/RepresentationKind"
          }
        },
        "sensitive": {
          "type": "boolean"
        },
        "exports": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ExportKind"
          }
        },
        "extensions": {
          "$ref": "#/$defs/JsonObject"
        }
      }
    },
    "RepresentationKind": {
      "type": "string",
      "enum": [
        "text",
        "code",
        "image",
        "table",
        "tree",
        "diff",
        "properties",
        "annotations",
        "previewDocument",
        "status"
      ]
    },
    "ExportKind": {
      "type": "string",
      "enum": [
        "copyText",
        "copyImage",
        "copyHtml",
        "save",
        "useAsInput",
        "openAsTab",
        "openInBrowser"
      ]
    },
    "CommonOptionFields": {
      "type": "object"
    },
    "OptionSpec": {
      "oneOf": [
        {
          "$ref": "#/$defs/BooleanOption"
        },
        {
          "$ref": "#/$defs/StringOption"
        },
        {
          "$ref": "#/$defs/IntegerOption"
        },
        {
          "$ref": "#/$defs/DecimalOption"
        },
        {
          "$ref": "#/$defs/EnumOption"
        },
        {
          "$ref": "#/$defs/ListOption"
        },
        {
          "$ref": "#/$defs/RecordOption"
        },
        {
          "$ref": "#/$defs/TaggedUnionOption"
        },
        {
          "$ref": "#/$defs/DocumentOption"
        },
        {
          "$ref": "#/$defs/SecretOption"
        },
        {
          "$ref": "#/$defs/ResourceOption"
        }
      ]
    },
    "BooleanOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "default",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "boolean"
        },
        "label": {
          "type": "string"
        },
        "default": {
          "type": "boolean"
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "StringOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "default",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "string"
        },
        "label": {
          "type": "string"
        },
        "default": {
          "type": "string"
        },
        "minLength": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "maxLength": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "pattern": {
          "type": "string"
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "IntegerOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "default",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "integer"
        },
        "label": {
          "type": "string"
        },
        "default": {
          "$ref": "#/$defs/DecimalInteger"
        },
        "minimum": {
          "$ref": "#/$defs/DecimalInteger"
        },
        "maximum": {
          "$ref": "#/$defs/DecimalInteger"
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "DecimalOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "default",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "decimal"
        },
        "label": {
          "type": "string"
        },
        "default": {
          "$ref": "#/$defs/DecimalValue"
        },
        "minimum": {
          "$ref": "#/$defs/DecimalValue"
        },
        "maximum": {
          "$ref": "#/$defs/DecimalValue"
        },
        "scale": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "EnumChoice": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "label"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/ChoiceIdentifier"
        },
        "label": {
          "type": "string"
        }
      }
    },
    "EnumOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "default",
        "choices",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "enum"
        },
        "label": {
          "type": "string"
        },
        "default": {
          "$ref": "#/$defs/ChoiceIdentifier"
        },
        "choices": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/EnumChoice"
          }
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "ValueShape": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "type"
      ],
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "boolean",
            "string",
            "integer",
            "decimal",
            "object"
          ]
        },
        "sensitive": {
          "type": "boolean"
        }
      }
    },
    "ListOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "default",
        "items",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "list"
        },
        "label": {
          "type": "string"
        },
        "default": {
          "type": "array"
        },
        "items": {
          "$ref": "#/$defs/ValueShape"
        },
        "minItems": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "maxItems": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "RecordOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "default",
        "fields",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "record"
        },
        "label": {
          "type": "string"
        },
        "default": {
          "$ref": "#/$defs/JsonObject"
        },
        "fields": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/OptionSpec"
          }
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "TaggedVariant": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "tag",
        "label",
        "fields"
      ],
      "properties": {
        "tag": {
          "$ref": "#/$defs/Identifier"
        },
        "label": {
          "type": "string"
        },
        "fields": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/OptionSpec"
          }
        }
      }
    },
    "TaggedUnionOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "default",
        "variants",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "taggedUnion"
        },
        "label": {
          "type": "string"
        },
        "default": {
          "$ref": "#/$defs/JsonObject"
        },
        "variants": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/TaggedVariant"
          }
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "DocumentOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "languages",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "document"
        },
        "label": {
          "type": "string"
        },
        "languages": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "SecretOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "secret"
        },
        "label": {
          "type": "string"
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "ResourceOption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "resourceKind",
        "persistence",
        "sensitive"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "const": "resource"
        },
        "label": {
          "type": "string"
        },
        "resourceKind": {
          "type": "string",
          "enum": [
            "file",
            "image"
          ]
        },
        "mime": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "persistence": {
          "$ref": "#/$defs/Persistence"
        },
        "sensitive": {
          "type": "boolean"
        },
        "group": {
          "type": "string"
        },
        "advanced": {
          "type": "boolean"
        },
        "rules": {
          "$ref": "#/$defs/ConditionalRules"
        }
      }
    },
    "Persistence": {
      "type": "string",
      "enum": [
        "workspace",
        "instance",
        "session",
        "none"
      ]
    },
    "ConditionalRules": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/ConditionalRule"
      }
    },
    "ConditionalRule": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "effect",
        "when"
      ],
      "properties": {
        "effect": {
          "type": "string",
          "enum": [
            "visible",
            "required",
            "enabled"
          ]
        },
        "when": {
          "$ref": "#/$defs/Condition"
        }
      }
    },
    "Condition": {
      "oneOf": [
        {
          "$ref": "#/$defs/PredicateCondition"
        },
        {
          "$ref": "#/$defs/AllCondition"
        },
        {
          "$ref": "#/$defs/AnyCondition"
        },
        {
          "$ref": "#/$defs/NotCondition"
        }
      ]
    },
    "PredicateCondition": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "optionId",
        "operator"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "predicate"
        },
        "optionId": {
          "$ref": "#/$defs/Identifier"
        },
        "operator": {
          "type": "string",
          "enum": [
            "equals",
            "notEquals",
            "in",
            "isSet"
          ]
        },
        "value": {}
      }
    },
    "AllCondition": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "conditions"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "all"
        },
        "conditions": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/Condition"
          }
        }
      }
    },
    "AnyCondition": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "conditions"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "any"
        },
        "conditions": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/Condition"
          }
        }
      }
    },
    "NotCondition": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "condition"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "not"
        },
        "condition": {
          "$ref": "#/$defs/Condition"
        }
      }
    },
    "TriggerPolicy": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "modes",
        "debounceMs"
      ],
      "properties": {
        "modes": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "enum": [
              "explicit",
              "inputChange",
              "selectionChange",
              "heldRepeat"
            ]
          }
        },
        "debounceMs": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "changedPorts": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Identifier"
          }
        }
      }
    },
    "LimitPolicy": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "maxInputBytes",
        "maxOutputBytes",
        "maxChunkBytes",
        "deadlineMs"
      ],
      "properties": {
        "maxInputBytes": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "maxOutputBytes": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "maxChunkBytes": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "deadlineMs": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "maxRows": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "maxNodes": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "maxAnnotations": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "maxPixels": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "maxPreviewBytes": {
          "$ref": "#/$defs/UnsignedDecimal"
        }
      }
    },
    "CachePolicy": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "mode"
      ],
      "properties": {
        "mode": {
          "type": "string",
          "enum": [
            "deterministic",
            "capturedContext",
            "disabled"
          ]
        },
        "varyBy": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "inputRevisions",
              "options",
              "pluginVersion",
              "engineVersion",
              "locale",
              "timezone",
              "clock",
              "randomness"
            ]
          }
        }
      }
    },
    "CapabilityId": {
      "type": "string",
      "enum": [
        "clipboard.readText",
        "clipboard.readImage",
        "clipboard.readHtml",
        "clipboard.writeText",
        "clipboard.writeImage",
        "clipboard.writeHtml",
        "documents.read",
        "documents.readRange",
        "documents.create",
        "artifacts.write",
        "files.import",
        "files.export",
        "secrets.use",
        "clock.capture",
        "randomness.seeded",
        "preview.scripts",
        "preview.network",
        "preview.navigation",
        "preview.localResources",
        "preview.externalBrowser"
      ]
    },
    "CapabilityRequest": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "required"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/CapabilityId"
        },
        "required": {
          "type": "boolean"
        },
        "reason": {
          "type": "string"
        },
        "policy": {
          "$ref": "#/$defs/JsonObject"
        }
      }
    },
    "WorkspaceKind": {
      "type": "string",
      "enum": [
        "singleEditor",
        "transform",
        "annotatedEditor",
        "linkedFields",
        "compare",
        "generator",
        "mediaPreview"
      ]
    },
    "WorkspaceSpec": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "kind",
        "bindings",
        "commands",
        "presentationSettings"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "kind": {
          "$ref": "#/$defs/WorkspaceKind"
        },
        "bindings": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/WorkspaceBinding"
          }
        },
        "commands": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CommandSpec"
          }
        },
        "presentationSettings": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/PresentationSetting"
          }
        },
        "trustedView": {
          "type": "string"
        },
        "extensions": {
          "$ref": "#/$defs/JsonObject"
        }
      }
    },
    "WorkspaceBinding": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "component"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "component": {
          "type": "string",
          "enum": [
            "editor",
            "field",
            "form",
            "output",
            "diagnostics",
            "properties",
            "table",
            "tree",
            "diff",
            "image",
            "preview",
            "annotations",
            "status"
          ]
        },
        "inputPort": {
          "$ref": "#/$defs/Identifier"
        },
        "outputPort": {
          "$ref": "#/$defs/Identifier"
        },
        "optionIds": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Identifier"
          }
        },
        "commandIds": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Identifier"
          }
        },
        "selectionSource": {
          "$ref": "#/$defs/Identifier"
        }
      }
    },
    "CommandSpec": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "label",
        "intent"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "label": {
          "type": "string"
        },
        "intent": {
          "type": "string",
          "enum": [
            "run",
            "copy",
            "save",
            "clear",
            "sample",
            "open",
            "paste",
            "swap",
            "cancel",
            "navigate",
            "openBrowser"
          ]
        },
        "operationId": {
          "$ref": "#/$defs/Identifier"
        },
        "inputPort": {
          "$ref": "#/$defs/Identifier"
        },
        "outputPort": {
          "$ref": "#/$defs/Identifier"
        },
        "semanticBinding": {
          "type": "string"
        }
      }
    },
    "PresentationSetting": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "type",
        "label",
        "default"
      ],
      "properties": {
        "id": {
          "$ref": "#/$defs/Identifier"
        },
        "type": {
          "type": "string",
          "enum": [
            "boolean",
            "enum",
            "splitRatio",
            "view"
          ]
        },
        "label": {
          "type": "string"
        },
        "default": {},
        "choices": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/EnumChoice"
          }
        },
        "persist": {
          "type": "boolean",
          "default": true
        }
      }
    },
    "DetectionSpec": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "mode",
        "maxProbeBytes"
      ],
      "properties": {
        "mode": {
          "type": "string",
          "enum": [
            "disabled",
            "suggest",
            "autoNewTab"
          ]
        },
        "maxProbeBytes": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "probeExecutor": {
          "$ref": "#/$defs/Identifier"
        }
      }
    },
    "TestDeclaration": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "requirementIds",
        "fixtures",
        "uiScenarios"
      ],
      "properties": {
        "requirementIds": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^DU-(?:0[1-9]|1[0-9]|2[0-7])$"
          }
        },
        "fixtures": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "uiScenarios": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "ExecuteRequest": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "apiVersion",
        "pluginId",
        "pluginVersion",
        "toolId",
        "operationId",
        "instanceId",
        "jobId",
        "generation",
        "inputs",
        "options",
        "trigger",
        "context",
        "requestedLimits"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "executeRequest"
        },
        "apiVersion": {
          "$ref": "#/$defs/ApiVersion"
        },
        "pluginId": {
          "$ref": "#/$defs/Identifier"
        },
        "pluginVersion": {
          "type": "string"
        },
        "toolId": {
          "$ref": "#/$defs/Identifier"
        },
        "operationId": {
          "$ref": "#/$defs/Identifier"
        },
        "instanceId": {
          "type": "string",
          "minLength": 1
        },
        "jobId": {
          "type": "string",
          "minLength": 1
        },
        "generation": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "inputs": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/InputBindingValue"
          }
        },
        "options": {
          "$ref": "#/$defs/JsonObject"
        },
        "trigger": {
          "$ref": "#/$defs/Trigger"
        },
        "context": {
          "$ref": "#/$defs/ExecutionContext"
        },
        "requestedLimits": {
          "$ref": "#/$defs/RequestedLimits"
        }
      }
    },
    "InputBinding": {
      "oneOf": [
        {
          "$ref": "#/$defs/DocumentRef"
        },
        {
          "$ref": "#/$defs/ValueRef"
        },
        {
          "$ref": "#/$defs/SelectionRef"
        },
        {
          "$ref": "#/$defs/SecretRef"
        },
        {
          "$ref": "#/$defs/ResourceRef"
        }
      ]
    },
    "InputBindingValue": {
      "oneOf": [
        {
          "$ref": "#/$defs/InputBinding"
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/InputBinding"
          }
        }
      ]
    },
    "DocumentRef": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "id",
        "revision",
        "byteLength",
        "contentKind",
        "encoding",
        "newline"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "document"
        },
        "id": {
          "type": "string"
        },
        "revision": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "byteLength": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "contentKind": {
          "type": "string",
          "enum": [
            "text",
            "image",
            "binary",
            "table",
            "scalar"
          ]
        },
        "mime": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "encoding": {
          "type": "string",
          "enum": [
            "utf8",
            "utf16Le",
            "utf16Be",
            "latin1",
            "binary"
          ]
        },
        "newline": {
          "type": "string",
          "enum": [
            "lf",
            "crLf",
            "cr",
            "mixed",
            "none",
            "unknown"
          ]
        }
      }
    },
    "ValueRef": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "value"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "value"
        },
        "value": {},
        "sensitive": {
          "type": "boolean"
        }
      }
    },
    "SelectionRef": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "documentId",
        "revision",
        "selectionEpoch",
        "startByte",
        "endByte"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "selection"
        },
        "documentId": {
          "type": "string"
        },
        "revision": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "selectionEpoch": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "startByte": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "endByte": {
          "$ref": "#/$defs/UnsignedDecimal"
        }
      }
    },
    "SecretRef": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "handle"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "secret"
        },
        "handle": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "ResourceRef": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "handle",
        "byteLength"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "file",
            "image"
          ]
        },
        "handle": {
          "type": "string",
          "minLength": 1
        },
        "byteLength": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "mime": {
          "type": "string"
        }
      }
    },
    "Trigger": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "origin",
        "revisionVector"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "explicit",
            "inputChange",
            "selectionChange",
            "heldRepeat"
          ]
        },
        "changedPort": {
          "$ref": "#/$defs/Identifier"
        },
        "origin": {
          "$ref": "#/$defs/Origin"
        },
        "revisionVector": {
          "$ref": "#/$defs/DecimalMap"
        }
      }
    },
    "Origin": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "userEdit",
            "derived",
            "file",
            "clipboard",
            "dragDrop",
            "generated",
            "command"
          ]
        },
        "sourceId": {
          "type": "string"
        },
        "parentJobId": {
          "type": "string"
        }
      }
    },
    "ExecutionContext": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "locale",
        "timezone"
      ],
      "properties": {
        "locale": {
          "type": "string"
        },
        "timezone": {
          "type": "string"
        },
        "capturedClock": {
          "type": "string",
          "format": "date-time"
        },
        "randomnessHandle": {
          "type": "string"
        }
      }
    },
    "RequestedLimits": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "maxOutputBytes": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "deadlineMs": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "maxPreviewBytes": {
          "$ref": "#/$defs/UnsignedDecimal"
        }
      }
    },
    "EventIdentity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "apiVersion",
        "pluginId",
        "pluginVersion",
        "toolId",
        "operationId",
        "instanceId",
        "jobId",
        "generation",
        "sequence"
      ],
      "properties": {
        "apiVersion": {
          "$ref": "#/$defs/ApiVersion"
        },
        "pluginId": {
          "$ref": "#/$defs/Identifier"
        },
        "pluginVersion": {
          "type": "string"
        },
        "toolId": {
          "$ref": "#/$defs/Identifier"
        },
        "operationId": {
          "$ref": "#/$defs/Identifier"
        },
        "instanceId": {
          "type": "string"
        },
        "jobId": {
          "type": "string"
        },
        "generation": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "sequence": {
          "$ref": "#/$defs/UnsignedDecimal"
        }
      }
    },
    "JobEvent": {
      "oneOf": [
        {
          "$ref": "#/$defs/AcceptedEvent"
        },
        {
          "$ref": "#/$defs/QueuedEvent"
        },
        {
          "$ref": "#/$defs/RunningEvent"
        },
        {
          "$ref": "#/$defs/ProgressEvent"
        },
        {
          "$ref": "#/$defs/OutputEvent"
        },
        {
          "$ref": "#/$defs/DiagnosticEvent"
        },
        {
          "$ref": "#/$defs/CompletedEvent"
        },
        {
          "$ref": "#/$defs/FailedEvent"
        },
        {
          "$ref": "#/$defs/CancelledEvent"
        },
        {
          "$ref": "#/$defs/CancelAcknowledgedEvent"
        }
      ]
    },
    "AcceptedEvent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "identity"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "accepted"
        },
        "identity": {
          "$ref": "#/$defs/EventIdentity"
        }
      }
    },
    "QueuedEvent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "identity"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "queued"
        },
        "identity": {
          "$ref": "#/$defs/EventIdentity"
        }
      }
    },
    "RunningEvent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "identity"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "running"
        },
        "identity": {
          "$ref": "#/$defs/EventIdentity"
        }
      }
    },
    "ProgressEvent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "identity",
        "phase",
        "processed"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "progress"
        },
        "identity": {
          "$ref": "#/$defs/EventIdentity"
        },
        "phase": {
          "type": "string"
        },
        "processed": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "total": {
          "$ref": "#/$defs/UnsignedDecimal"
        }
      }
    },
    "OutputEvent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "identity",
        "portId",
        "output"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "output"
        },
        "identity": {
          "$ref": "#/$defs/EventIdentity"
        },
        "portId": {
          "$ref": "#/$defs/Identifier"
        },
        "output": {
          "$ref": "#/$defs/OutputDescriptor"
        }
      }
    },
    "DiagnosticEvent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "identity",
        "diagnostic"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "diagnostic"
        },
        "identity": {
          "$ref": "#/$defs/EventIdentity"
        },
        "diagnostic": {
          "$ref": "#/$defs/Diagnostic"
        }
      }
    },
    "CompletedEvent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "identity",
        "outputs",
        "diagnostics",
        "stats",
        "provenance"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "completed"
        },
        "identity": {
          "$ref": "#/$defs/EventIdentity"
        },
        "outputs": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/OutputDescriptor"
          }
        },
        "diagnostics": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Diagnostic"
          }
        },
        "stats": {
          "$ref": "#/$defs/Stats"
        },
        "provenance": {
          "$ref": "#/$defs/Provenance"
        }
      }
    },
    "FailedEvent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "identity",
        "error",
        "diagnostics"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "failed"
        },
        "identity": {
          "$ref": "#/$defs/EventIdentity"
        },
        "error": {
          "$ref": "#/$defs/ContractError"
        },
        "diagnostics": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Diagnostic"
          }
        }
      }
    },
    "CancelledEvent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "identity",
        "reason",
        "cleanupComplete"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "cancelled"
        },
        "identity": {
          "$ref": "#/$defs/EventIdentity"
        },
        "reason": {
          "type": "string",
          "enum": [
            "user",
            "superseded",
            "resourceLimit",
            "shutdown",
            "timeout"
          ]
        },
        "cleanupComplete": {
          "type": "boolean"
        }
      }
    },
    "CancelAcknowledgedEvent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "identity"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "const": "cancelAcknowledged"
        },
        "identity": {
          "$ref": "#/$defs/EventIdentity"
        }
      }
    },
    "OutputDescriptor": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "representation",
        "complete",
        "availableViews",
        "exportFormats",
        "sensitive"
      ],
      "properties": {
        "representation": {
          "$ref": "#/$defs/RepresentationKind"
        },
        "artifactRef": {
          "$ref": "#/$defs/ArtifactRef"
        },
        "boundedValue": {},
        "language": {
          "type": "string"
        },
        "mime": {
          "type": "string"
        },
        "complete": {
          "type": "boolean"
        },
        "preview": {
          "$ref": "#/$defs/PreviewDescriptor"
        },
        "availableViews": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/RepresentationKind"
          }
        },
        "exportFormats": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ExportKind"
          }
        },
        "sensitive": {
          "type": "boolean"
        }
      }
    },
    "ArtifactRef": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "handle",
        "byteLength",
        "contentHash"
      ],
      "properties": {
        "handle": {
          "type": "string"
        },
        "byteLength": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "contentHash": {
          "type": "string"
        }
      }
    },
    "PreviewDescriptor": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "truncated",
        "offset",
        "byteLength"
      ],
      "properties": {
        "truncated": {
          "type": "boolean"
        },
        "offset": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "byteLength": {
          "$ref": "#/$defs/UnsignedDecimal"
        }
      }
    },
    "Diagnostic": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "code",
        "severity",
        "message"
      ],
      "properties": {
        "code": {
          "$ref": "#/$defs/Identifier"
        },
        "severity": {
          "type": "string",
          "enum": [
            "hint",
            "info",
            "warning",
            "error"
          ]
        },
        "message": {
          "type": "string"
        },
        "source": {
          "$ref": "#/$defs/SourceSpan"
        },
        "related": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/SourceSpan"
          }
        },
        "data": {
          "$ref": "#/$defs/JsonObject"
        }
      }
    },
    "SourceSpan": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "documentId",
        "revision",
        "startByte",
        "endByte"
      ],
      "properties": {
        "documentId": {
          "type": "string"
        },
        "revision": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "startByte": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "endByte": {
          "$ref": "#/$defs/UnsignedDecimal"
        }
      }
    },
    "Stats": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "elapsedMs",
        "inputBytes",
        "outputBytes"
      ],
      "properties": {
        "elapsedMs": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "inputBytes": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "outputBytes": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "rows": {
          "$ref": "#/$defs/UnsignedDecimal"
        },
        "annotations": {
          "$ref": "#/$defs/UnsignedDecimal"
        }
      }
    },
    "Provenance": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "pluginId",
        "pluginVersion",
        "operationId",
        "engine",
        "engineVersion",
        "inputRevisions",
        "optionsDigest"
      ],
      "properties": {
        "pluginId": {
          "$ref": "#/$defs/Identifier"
        },
        "pluginVersion": {
          "type": "string"
        },
        "operationId": {
          "$ref": "#/$defs/Identifier"
        },
        "engine": {
          "type": "string"
        },
        "engineVersion": {
          "type": "string"
        },
        "syntax": {
          "type": "string"
        },
        "inputRevisions": {
          "$ref": "#/$defs/DecimalMap"
        },
        "optionsDigest": {
          "type": "string"
        },
        "capturedClock": {
          "type": "string"
        },
        "randomnessId": {
          "type": "string"
        }
      }
    },
    "ContractError": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "$ref": "#/$defs/Identifier"
        },
        "message": {
          "type": "string"
        },
        "retryable": {
          "type": "boolean"
        },
        "details": {
          "$ref": "#/$defs/JsonObject"
        }
      }
    }
  }
} as const;